//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

//[assembly: System.Reflection.AssemblyTitle("NewPlatform.Flexberry.ORM.ODataService.Tests")]
//[assembly: System.Reflection.AssemblyDescription("NewPlatform.Flexberry.ORM.ODataService.Tests")]
//[assembly: System.Reflection.AssemblyConfiguration("")]
//[assembly: System.Reflection.AssemblyCompany("New platform Ltd")]
//[assembly: System.Reflection.AssemblyProduct("NewPlatform.Flexberry.ORM.ODataService.Tests")]
//[assembly: System.Reflection.AssemblyCopyright("(c) 2004-2018. NewPlatform Ltd. All rights reserved.")]
//[assembly: System.Reflection.AssemblyTrademark("Flexberry")]
//[assembly: System.Reflection.AssemblyCulture("")]
//[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
//[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]

