version: "3.2"
services:
  postgres:
    image: flexberry/alt.p8-postgresql:12
    ports:
     - 15432:5432
    volumes:
     - db:/var/lib/pgsql/data/
     - backups:/var/lib/pgsql/backups  
    environment:
      WALG: file
volumes:
  db:
  backups:

