#!/bin/bash

# gitlab-runner data directory
DATA_DIR="/etc/gitlab-runner"
CONFIG_FILE=${CONFIG_FILE:-$DATA_DIR/config.toml}
# custom certificate authority path
CA_CERTIFICATES_PATH=${CA_CERTIFICATES_PATH:-$DATA_DIR/certs/ca.crt}
LOCAL_CA_PATH="/usr/local/share/ca-certificates/ca.crt"

update_ca() {
  echo "Updating CA certificates..."
  cp "${CA_CERTIFICATES_PATH}" "${LOCAL_CA_PATH}"
  update-ca-certificates --fresh >/dev/null
}

if [ -f "${CA_CERTIFICATES_PATH}" ]; then
  # update the ca if the custom ca is different than the current
  cmp --silent "${CA_CERTIFICATES_PATH}" "${LOCAL_CA_PATH}" || update_ca
fi

if [ -z "$CI_SERVER_TOKEN_NAME" ]
then
  CI_SERVER_TOKEN_NAME=gitlab_registry_token
fi

read CI_SERVER_TOKEN < /run/secrets/$CI_SERVER_TOKEN_NAME

(
set -x
sleep 2

until gitlab-runner register -n \
  --url $CI_SERVER_URL \
  --clone-url $CI_SERVER_URL \
  --registration-token $CI_SERVER_TOKEN \
  --executor docker \
  --description "Shared GitLab Runner with Docker Executor" \
  --tag-list "docker-executor" \
  --docker-image "docker:19.03.5" \
  --docker-volumes /var/run/docker.sock:/var/run/docker.sock
do
  sleep 5
done
) &

# launch gitlab-runner passing all arguments
exec gitlab-runner "$@"
