version: '3.2'

services:
  pentaho:
    image: flexberry/pentaho-saiku$BI_IMAGE_TAG
    command: /biserver-ce/start-pentaho.sh
    ports:
      - "${SERVER_PROM_PORT}:1234"
      - "${SERVER_HTTP_PORT}:8080"
      - "${SERVER_AJP_PORT}:8009"
    volumes:
      - hidden:/biserver-ce/.pentaho/
      - hsqldb:/biserver-ce/data/hsqldb/
      - logs:/biserver-ce/tomcat/logs
      - repository:/biserver-ce/pentaho-solutions/system/jackrabbit/repository
      - tmp:/biserver-ce/tmp

    environment:
      APPLY_PATCHES: 'Y'
      BI_JAVA_OPTS: '${BI_JAVA_OPTS}'
      HOST_USER_ID: ${HOST_USER_ID}
      STORAGE_TYPE: ${STORAGE_TYPE}
      PDI_HADOOP_CONFIG: ${PDI_HADOOP_CONFIG}
      PDI_MAX_LOG_LINES: ${PDI_MAX_LOG_LINES}
      PDI_MAX_LOG_TIMEOUT: ${PDI_MAX_LOG_TIMEOUT}
      PDI_MAX_OBJ_TIMEOUT: ${PDI_MAX_OBJ_TIMEOUT}
      SERVER_NAME: ${SERVER_NAME}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_EXT_PORT}
      DISABLED_TOOLS: ${DISABLED_TOOLS}

volumes:
  hidden:
  hsqldb:
  repository:
  logs:
  tmp:
