//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// CatsBS.
    /// </summary>
    // *** Start programmer edit section *** (CatsBS CustomAttributes)

    // *** End programmer edit section *** (CatsBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class CatsBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (CatsBS CustomMembers)

        // *** End programmer edit section *** (CatsBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateПерелом CustomAttributes)

        // *** End programmer edit section *** (OnUpdateПерелом CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateПерелом(NewPlatform.Flexberry.ORM.ODataService.Tests.Перелом UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateПерелом)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateПерелом)
        }
        
        // *** Start programmer edit section *** (OnUpdateЛапа CustomAttributes)

        // *** End programmer edit section *** (OnUpdateЛапа CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateЛапа(NewPlatform.Flexberry.ORM.ODataService.Tests.Лапа UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateЛапа)
            if (UpdatedObject.Размер == 100899)
            {
                // Это сообщение используется в тесте BatchUpdateErrorHandlingTest.
                throw new Exception("Недопустимый размер кошачьей лапы!");
            }

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateЛапа)
        }
        
        // *** Start programmer edit section *** (OnUpdateКошка CustomAttributes)

        // *** End programmer edit section *** (OnUpdateКошка CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateКошка(NewPlatform.Flexberry.ORM.ODataService.Tests.Кошка UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateКошка)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateКошка)
        }
    }
}
