//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// БерлогаБС.
    /// </summary>
    // *** Start programmer edit section *** (БерлогаБС CustomAttributes)

    // *** End programmer edit section *** (БерлогаБС CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class БерлогаБС : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (БерлогаБС CustomMembers)

        // *** End programmer edit section *** (БерлогаБС CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateБерлога CustomAttributes)

        // *** End programmer edit section *** (OnUpdateБерлога CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateБерлога(NewPlatform.Flexberry.ORM.ODataService.Tests.Берлога UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateБерлога)
            if (UpdatedObject.GetStatus() == ICSSoft.STORMNET.ObjectStatus.Created)
            {
                UpdatedObject.ПолеБС = "Object created.";

            }
            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateБерлога)
        }
    }
}
