//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ЛесБС.
    /// </summary>
    // *** Start programmer edit section *** (ЛесБС CustomAttributes)

    // *** End programmer edit section *** (ЛесБС CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ЛесБС : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (ЛесБС CustomMembers)

        // *** End programmer edit section *** (ЛесБС CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateЛес CustomAttributes)

        // *** End programmer edit section *** (OnUpdateЛес CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateЛес(NewPlatform.Flexberry.ORM.ODataService.Tests.Лес UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateЛес)

            return new ICSSoft.STORMNET.DataObject[] { UpdatedObject };
            // *** End programmer edit section *** (OnUpdateЛес)
        }
    }
}
