//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// МедведьБС.
    /// </summary>
    // *** Start programmer edit section *** (МедведьБС CustomAttributes)

    // *** End programmer edit section *** (МедведьБС CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class МедведьБС : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (МедведьБС CustomMembers)

        // *** End programmer edit section *** (МедведьБС CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateМедведь CustomAttributes)

        // *** End programmer edit section *** (OnUpdateМедведь CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateМедведь(NewPlatform.Flexberry.ORM.ODataService.Tests.Медведь UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateМедведь)
            if (UpdatedObject.GetStatus() == ICSSoft.STORMNET.ObjectStatus.Created)
            {
                UpdatedObject.ПолеБС = "Object created.";
                
            }
            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateМедведь)
        }
    }
}
