#!/bin/sh

set -x
ifs=$IFS
IFS=:
IFS=:/
set -- $IMAGE_NAME
IFS=$ifs
IMAGE="$2/$3"
gitTag=$4

IFS=-
set -- $gitTag
IFS=$ifs
version=
case $# in
  2)
    version=$1
    build=$2
    echo "Service version $version, build version $build"
    fullTag="${version}-"
    ;;
  1)
    build=$1
    echo "Build version $build"
    fullTag=
  ;;
  *)
    echo "Incorrect verison format in tag. Tags must have a look ${IMAGE}_[ServiceVersion-]BuildVersion"
    exit 3
esac

latestImage="$IMAGE_NAME:latest"
versionImage=
if [ -n "$version" ]
then
  versionImage="$IMAGE_NAME:$version"
fi
IFS=.
set -- $build
IFS=$ifs
major=$1
minor=$2
patch=$3

majorImage="$IMAGE_NAME:$fullTag$major"
minorImage="$IMAGE_NAME:$fullTag$major.$minor"

for image in $latestImage $majorImage $minorImage $versionImage
do
  docker tag $IMAGE_NAME $image
  docker push $image
done