CREATE USER FLEXBERRY_ORM_TESTER IDENTIFIED BY sa3dfE DEFAULT TABLESPACE users  quota unlimited on users  TEMPORARY TABLESPACE temp;
GRANT CREATE SESSION TO FLEXBERRY_ORM_TESTER;
GRANT CREATE TABLE TO FLEXBERRY_ORM_TESTER;
GRANT CREATE USER TO FLEXBERRY_ORM_TESTER;
GRANT GRANT ANY PRIVILEGE TO FLEXBERRY_ORM_TESTER;
QUIT
