version: '3.2'

services:
  clickhouse:
    image: flexberry/clickhouse-official
        ports:
      - "8123:8123"
      - "19000:9000"
      - "19009:9009"
    volumes:
      - clickhouse:/var/lib/clickhouse
      - clickhouse-config:/etc/clickhouse-server/
      - /etc/localtime:/etc/localtime 
    environment:
      PGDatabase: ${PGDatabase}
      PGServername: ${PGServername}
      PGUserName: ${PGUserName}
      PGPassword: ${PGPassword}
      PGPort: ${PGPort}
      PGProtocol: ${PGProtocol}
      PGDicrionaries: ${PGDicrionaries}
      PGBigTable: ${PGBigTable}