version: '3.2'

services:
  clickhouse:
    image: flexberry/clickhouse-official
        ports:
      - "8123:8123"
      - "19000:9000"
      - "19009:9009"
    volumes:
      - clickhousedb:/var/lib/clickhouse
