version: '3.2'

services:
  clickhouse:
    image: flexberry/clickhouse-official
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhousedb:/var/lib/clickhouse
      
volumes:
  clickhousedb:
