version: "3.2"
services:
  postgres:
    image: flexberry/alt.p8-postgresql:latest
    ports:
     - 5432:5432
    volumes:
     - db:/var/lib/pgsql/data/
    environment:
      - POSTGRES_max_connections=${POSTGRES_max_connections}
    deploy:
      placement:
        constraints:
          - 'node.role==manager'

volumes:
  db:
