//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// TestMaster.
    /// </summary>
    // *** Start programmer edit section *** (TestMaster CustomAttributes)

    // *** End programmer edit section *** (TestMaster CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("TestMasterE", new string[] {
            "TestMasterName"})]
    [View("TestMasterL", new string[] {
            "TestMasterName"})]
    public class TestMaster : ICSSoft.STORMNET.DataObject
    {
        
        private string fTestMasterName;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfTestDetailWithCicle fTestDetailWithCicle;
        
        // *** Start programmer edit section *** (TestMaster CustomMembers)

        // *** End programmer edit section *** (TestMaster CustomMembers)

        
        /// <summary>
        /// TestMasterName.
        /// </summary>
        // *** Start programmer edit section *** (TestMaster.TestMasterName CustomAttributes)

        // *** End programmer edit section *** (TestMaster.TestMasterName CustomAttributes)
        [StrLen(255)]
        public virtual string TestMasterName
        {
            get
            {
                // *** Start programmer edit section *** (TestMaster.TestMasterName Get start)

                // *** End programmer edit section *** (TestMaster.TestMasterName Get start)
                string result = this.fTestMasterName;
                // *** Start programmer edit section *** (TestMaster.TestMasterName Get end)

                // *** End programmer edit section *** (TestMaster.TestMasterName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TestMaster.TestMasterName Set start)

                // *** End programmer edit section *** (TestMaster.TestMasterName Set start)
                this.fTestMasterName = value;
                // *** Start programmer edit section *** (TestMaster.TestMasterName Set end)

                // *** End programmer edit section *** (TestMaster.TestMasterName Set end)
            }
        }
        
        /// <summary>
        /// TestMaster.
        /// </summary>
        // *** Start programmer edit section *** (TestMaster.TestDetailWithCicle CustomAttributes)

        // *** End programmer edit section *** (TestMaster.TestDetailWithCicle CustomAttributes)
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfTestDetailWithCicle TestDetailWithCicle
        {
            get
            {
                // *** Start programmer edit section *** (TestMaster.TestDetailWithCicle Get start)

                // *** End programmer edit section *** (TestMaster.TestDetailWithCicle Get start)
                if ((this.fTestDetailWithCicle == null))
                {
                    this.fTestDetailWithCicle = new NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfTestDetailWithCicle(this);
                }
                NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfTestDetailWithCicle result = this.fTestDetailWithCicle;
                // *** Start programmer edit section *** (TestMaster.TestDetailWithCicle Get end)

                // *** End programmer edit section *** (TestMaster.TestDetailWithCicle Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TestMaster.TestDetailWithCicle Set start)

                // *** End programmer edit section *** (TestMaster.TestDetailWithCicle Set start)
                this.fTestDetailWithCicle = value;
                // *** Start programmer edit section *** (TestMaster.TestDetailWithCicle Set end)

                // *** End programmer edit section *** (TestMaster.TestDetailWithCicle Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "TestMasterE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TestMasterE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TestMasterE", typeof(NewPlatform.Flexberry.ORM.ODataService.Tests.TestMaster));
                }
            }
            
            /// <summary>
            /// "TestMasterL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TestMasterL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TestMasterL", typeof(NewPlatform.Flexberry.ORM.ODataService.Tests.TestMaster));
                }
            }
        }
    }
}
