//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Котенок.
    /// </summary>
    // *** Start programmer edit section *** (Котенок CustomAttributes)

    // *** End programmer edit section *** (Котенок CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Котенок : ICSSoft.STORMNET.DataObject
    {
        
        private string fКличкаКотенка;
        
        private int fГлупость;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.Кошка fКошка;
        
        // *** Start programmer edit section *** (Котенок CustomMembers)

        // *** End programmer edit section *** (Котенок CustomMembers)

        
        /// <summary>
        /// КличкаКотенка.
        /// </summary>
        // *** Start programmer edit section *** (Котенок.КличкаКотенка CustomAttributes)

        // *** End programmer edit section *** (Котенок.КличкаКотенка CustomAttributes)
        [StrLen(255)]
        public virtual string КличкаКотенка
        {
            get
            {
                // *** Start programmer edit section *** (Котенок.КличкаКотенка Get start)

                // *** End programmer edit section *** (Котенок.КличкаКотенка Get start)
                string result = this.fКличкаКотенка;
                // *** Start programmer edit section *** (Котенок.КличкаКотенка Get end)

                // *** End programmer edit section *** (Котенок.КличкаКотенка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Котенок.КличкаКотенка Set start)

                // *** End programmer edit section *** (Котенок.КличкаКотенка Set start)
                this.fКличкаКотенка = value;
                // *** Start programmer edit section *** (Котенок.КличкаКотенка Set end)

                // *** End programmer edit section *** (Котенок.КличкаКотенка Set end)
            }
        }
        
        /// <summary>
        /// Глупость.
        /// </summary>
        // *** Start programmer edit section *** (Котенок.Глупость CustomAttributes)

        // *** End programmer edit section *** (Котенок.Глупость CustomAttributes)
        public virtual int Глупость
        {
            get
            {
                // *** Start programmer edit section *** (Котенок.Глупость Get start)

                // *** End programmer edit section *** (Котенок.Глупость Get start)
                int result = this.fГлупость;
                // *** Start programmer edit section *** (Котенок.Глупость Get end)

                // *** End programmer edit section *** (Котенок.Глупость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Котенок.Глупость Set start)

                // *** End programmer edit section *** (Котенок.Глупость Set start)
                this.fГлупость = value;
                // *** Start programmer edit section *** (Котенок.Глупость Set end)

                // *** End programmer edit section *** (Котенок.Глупость Set end)
            }
        }
        
        /// <summary>
        /// Котенок.
        /// </summary>
        // *** Start programmer edit section *** (Котенок.Кошка CustomAttributes)

        // *** End programmer edit section *** (Котенок.Кошка CustomAttributes)
        [NotNull()]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.Кошка Кошка
        {
            get
            {
                // *** Start programmer edit section *** (Котенок.Кошка Get start)

                // *** End programmer edit section *** (Котенок.Кошка Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.Кошка result = this.fКошка;
                // *** Start programmer edit section *** (Котенок.Кошка Get end)

                // *** End programmer edit section *** (Котенок.Кошка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Котенок.Кошка Set start)

                // *** End programmer edit section *** (Котенок.Кошка Set start)
                this.fКошка = value;
                // *** Start programmer edit section *** (Котенок.Кошка Set end)

                // *** End programmer edit section *** (Котенок.Кошка Set end)
            }
        }
    }
}
