//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Мастер2.
    /// </summary>
    // *** Start programmer edit section *** (Мастер2 CustomAttributes)

    // *** End programmer edit section *** (Мастер2 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Мастер2 : ICSSoft.STORMNET.DataObject
    {
        
        private int fсвойство2;
        
        // *** Start programmer edit section *** (Мастер2 CustomMembers)

        // *** End programmer edit section *** (Мастер2 CustomMembers)

        
        /// <summary>
        /// свойство2.
        /// </summary>
        // *** Start programmer edit section *** (Мастер2.свойство2 CustomAttributes)
        [PublishName("Property2Alias")]
        // *** End programmer edit section *** (Мастер2.свойство2 CustomAttributes)
        public virtual int свойство2
        {
            get
            {
                // *** Start programmer edit section *** (Мастер2.свойство2 Get start)

                // *** End programmer edit section *** (Мастер2.свойство2 Get start)
                int result = this.fсвойство2;
                // *** Start programmer edit section *** (Мастер2.свойство2 Get end)

                // *** End programmer edit section *** (Мастер2.свойство2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Мастер2.свойство2 Set start)

                // *** End programmer edit section *** (Мастер2.свойство2 Set start)
                this.fсвойство2 = value;
                // *** Start programmer edit section *** (Мастер2.свойство2 Set end)

                // *** End programmer edit section *** (Мастер2.свойство2 Set end)
            }
        }
    }
}
