//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ТипКошки.
    /// </summary>
    // *** Start programmer edit section *** (ТипКошки CustomAttributes)

    // *** End programmer edit section *** (ТипКошки CustomAttributes)
    public enum ТипКошки
    {
        
        // *** Start programmer edit section *** (ТипКошки.НетЗначения CustomAttributes)

        // *** End programmer edit section *** (ТипКошки.НетЗначения CustomAttributes)
        НетЗначения,
        
        // *** Start programmer edit section *** (ТипКошки.Дикая CustomAttributes)

        // *** End programmer edit section *** (ТипКошки.Дикая CustomAttributes)
        Дикая,
        
        // *** Start programmer edit section *** (ТипКошки.Домашняя CustomAttributes)

        // *** End programmer edit section *** (ТипКошки.Домашняя CustomAttributes)
        Домашняя,
    }
}
