//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Daughter.
    /// </summary>
    // *** Start programmer edit section *** (Daughter CustomAttributes)

    // *** End programmer edit section *** (Daughter CustomAttributes)
    [PublishName("Daughter")]
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Daughter : NewPlatform.Flexberry.ORM.ODataService.Tests.Child
    {
        
        private string fDressColor;
        
        // *** Start programmer edit section *** (Daughter CustomMembers)

        // *** End programmer edit section *** (Daughter CustomMembers)

        
        /// <summary>
        /// DressColor.
        /// </summary>
        // *** Start programmer edit section *** (Daughter.DressColor CustomAttributes)

        // *** End programmer edit section *** (Daughter.DressColor CustomAttributes)
        [StrLen(255)]
        public virtual string DressColor
        {
            get
            {
                // *** Start programmer edit section *** (Daughter.DressColor Get start)

                // *** End programmer edit section *** (Daughter.DressColor Get start)
                string result = this.fDressColor;
                // *** Start programmer edit section *** (Daughter.DressColor Get end)

                // *** End programmer edit section *** (Daughter.DressColor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Daughter.DressColor Set start)

                // *** End programmer edit section *** (Daughter.DressColor Set start)
                this.fDressColor = value;
                // *** Start programmer edit section *** (Daughter.DressColor Set end)

                // *** End programmer edit section *** (Daughter.DressColor Set end)
            }
        }
    }
}
