//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Driver.
    /// </summary>
    // *** Start programmer edit section *** (Driver CustomAttributes)

    // *** End programmer edit section *** (Driver CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AllData", new string[] {
            "Name as \'Name\'",
            "CarCount as \'CarCount\'",
            "Documents as \'Documents\'"})]
    public class Driver : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private int fCarCount;
        
        private bool fDocuments;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfCar fCar;
        
        // *** Start programmer edit section *** (Driver CustomMembers)

        // *** End programmer edit section *** (Driver CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Driver.Name CustomAttributes)

        // *** End programmer edit section *** (Driver.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Driver.Name Get start)

                // *** End programmer edit section *** (Driver.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Driver.Name Get end)

                // *** End programmer edit section *** (Driver.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Driver.Name Set start)

                // *** End programmer edit section *** (Driver.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Driver.Name Set end)

                // *** End programmer edit section *** (Driver.Name Set end)
            }
        }
        
        /// <summary>
        /// CarCount.
        /// </summary>
        // *** Start programmer edit section *** (Driver.CarCount CustomAttributes)

        // *** End programmer edit section *** (Driver.CarCount CustomAttributes)
        public virtual int CarCount
        {
            get
            {
                // *** Start programmer edit section *** (Driver.CarCount Get start)

                // *** End programmer edit section *** (Driver.CarCount Get start)
                int result = this.fCarCount;
                // *** Start programmer edit section *** (Driver.CarCount Get end)

                // *** End programmer edit section *** (Driver.CarCount Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Driver.CarCount Set start)

                // *** End programmer edit section *** (Driver.CarCount Set start)
                this.fCarCount = value;
                // *** Start programmer edit section *** (Driver.CarCount Set end)

                // *** End programmer edit section *** (Driver.CarCount Set end)
            }
        }
        
        /// <summary>
        /// Documents.
        /// </summary>
        // *** Start programmer edit section *** (Driver.Documents CustomAttributes)

        // *** End programmer edit section *** (Driver.Documents CustomAttributes)
        public virtual bool Documents
        {
            get
            {
                // *** Start programmer edit section *** (Driver.Documents Get start)

                // *** End programmer edit section *** (Driver.Documents Get start)
                bool result = this.fDocuments;
                // *** Start programmer edit section *** (Driver.Documents Get end)

                // *** End programmer edit section *** (Driver.Documents Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Driver.Documents Set start)

                // *** End programmer edit section *** (Driver.Documents Set start)
                this.fDocuments = value;
                // *** Start programmer edit section *** (Driver.Documents Set end)

                // *** End programmer edit section *** (Driver.Documents Set end)
            }
        }
        
        /// <summary>
        /// Driver.
        /// </summary>
        // *** Start programmer edit section *** (Driver.Car CustomAttributes)

        // *** End programmer edit section *** (Driver.Car CustomAttributes)
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfCar Car
        {
            get
            {
                // *** Start programmer edit section *** (Driver.Car Get start)

                // *** End programmer edit section *** (Driver.Car Get start)
                if ((this.fCar == null))
                {
                    this.fCar = new NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfCar(this);
                }
                NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfCar result = this.fCar;
                // *** Start programmer edit section *** (Driver.Car Get end)

                // *** End programmer edit section *** (Driver.Car Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Driver.Car Set start)

                // *** End programmer edit section *** (Driver.Car Set start)
                this.fCar = value;
                // *** Start programmer edit section *** (Driver.Car Set end)

                // *** End programmer edit section *** (Driver.Car Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AllData" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AllData
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AllData", typeof(NewPlatform.Flexberry.ORM.ODataService.Tests.Driver));
                }
            }
        }
    }
}
