//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Son.
    /// </summary>
    // *** Start programmer edit section *** (Son CustomAttributes)

    // *** End programmer edit section *** (Son CustomAttributes)
    [PublishName("Son")]
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Son : NewPlatform.Flexberry.ORM.ODataService.Tests.Child
    {
        
        private string fSuspendersColor;
        
        // *** Start programmer edit section *** (Son CustomMembers)

        // *** End programmer edit section *** (Son CustomMembers)

        
        /// <summary>
        /// SuspendersColor.
        /// </summary>
        // *** Start programmer edit section *** (Son.SuspendersColor CustomAttributes)

        // *** End programmer edit section *** (Son.SuspendersColor CustomAttributes)
        [StrLen(255)]
        public virtual string SuspendersColor
        {
            get
            {
                // *** Start programmer edit section *** (Son.SuspendersColor Get start)

                // *** End programmer edit section *** (Son.SuspendersColor Get start)
                string result = this.fSuspendersColor;
                // *** Start programmer edit section *** (Son.SuspendersColor Get end)

                // *** End programmer edit section *** (Son.SuspendersColor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Son.SuspendersColor Set start)

                // *** End programmer edit section *** (Son.SuspendersColor Set start)
                this.fSuspendersColor = value;
                // *** Start programmer edit section *** (Son.SuspendersColor Set end)

                // *** End programmer edit section *** (Son.SuspendersColor Set end)
            }
        }
    }
}
