//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Пол.
    /// </summary>
    // *** Start programmer edit section *** (tПол CustomAttributes)

    // *** End programmer edit section *** (tПол CustomAttributes)
    public enum tПол
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tПол.Мужской CustomAttributes)

        // *** End programmer edit section *** (tПол.Мужской CustomAttributes)
        Мужской,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tПол.Женский CustomAttributes)

        // *** End programmer edit section *** (tПол.Женский CustomAttributes)
        Женский,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tПол.НеПонятно CustomAttributes)

        // *** End programmer edit section *** (tПол.НеПонятно CustomAttributes)
        НеПонятно,
    }
}
