//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Библиотека.
    /// </summary>
    // *** Start programmer edit section *** (Библиотека CustomAttributes)

    // *** End programmer edit section *** (Библиотека CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Eview", new string[] {
            "Адрес as \'Адрес\'"})]
    [AssociatedDetailViewAttribute("Eview", "Журнал", "Dжурнал", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("Eview", "Книга", "Dкнига", true, "", "", true, new string[] {
            ""})]
    public class Библиотека : ICSSoft.STORMNET.DataObject
    {
        
        private string fАдрес;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfКнига fКнига;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfЖурнал fЖурнал;
        
        // *** Start programmer edit section *** (Библиотека CustomMembers)

        // *** End programmer edit section *** (Библиотека CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Библиотека.Адрес CustomAttributes)

        // *** End programmer edit section *** (Библиотека.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Библиотека.Адрес Get start)

                // *** End programmer edit section *** (Библиотека.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Библиотека.Адрес Get end)

                // *** End programmer edit section *** (Библиотека.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Библиотека.Адрес Set start)

                // *** End programmer edit section *** (Библиотека.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Библиотека.Адрес Set end)

                // *** End programmer edit section *** (Библиотека.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Библиотека.
        /// </summary>
        // *** Start programmer edit section *** (Библиотека.Книга CustomAttributes)

        // *** End programmer edit section *** (Библиотека.Книга CustomAttributes)
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfКнига Книга
        {
            get
            {
                // *** Start programmer edit section *** (Библиотека.Книга Get start)

                // *** End programmer edit section *** (Библиотека.Книга Get start)
                if ((this.fКнига == null))
                {
                    this.fКнига = new NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfКнига(this);
                }
                NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfКнига result = this.fКнига;
                // *** Start programmer edit section *** (Библиотека.Книга Get end)

                // *** End programmer edit section *** (Библиотека.Книга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Библиотека.Книга Set start)

                // *** End programmer edit section *** (Библиотека.Книга Set start)
                this.fКнига = value;
                // *** Start programmer edit section *** (Библиотека.Книга Set end)

                // *** End programmer edit section *** (Библиотека.Книга Set end)
            }
        }
        
        /// <summary>
        /// Библиотека.
        /// </summary>
        // *** Start programmer edit section *** (Библиотека.Журнал CustomAttributes)

        // *** End programmer edit section *** (Библиотека.Журнал CustomAttributes)
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfЖурнал Журнал
        {
            get
            {
                // *** Start programmer edit section *** (Библиотека.Журнал Get start)

                // *** End programmer edit section *** (Библиотека.Журнал Get start)
                if ((this.fЖурнал == null))
                {
                    this.fЖурнал = new NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfЖурнал(this);
                }
                NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfЖурнал result = this.fЖурнал;
                // *** Start programmer edit section *** (Библиотека.Журнал Get end)

                // *** End programmer edit section *** (Библиотека.Журнал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Библиотека.Журнал Set start)

                // *** End programmer edit section *** (Библиотека.Журнал Set start)
                this.fЖурнал = value;
                // *** Start programmer edit section *** (Библиотека.Журнал Set end)

                // *** End programmer edit section *** (Библиотека.Журнал Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Eview" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Eview
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Eview", typeof(NewPlatform.Flexberry.ORM.ODataService.Tests.Библиотека));
                }
            }
        }
    }
}
