//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Детейл2.
    /// </summary>
    // *** Start programmer edit section *** (Детейл2 CustomAttributes)
    [PublishName("NewPlatform.Flexberry.ORM.ODataService.Tests.Detail2Alias", "Detail2Aliases")]
    // *** End programmer edit section *** (Детейл2 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Детейл2 : ICSSoft.STORMNET.DataObject
    {
        
        private string fprop2;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.Детейл fДетейл;
        
        // *** Start programmer edit section *** (Детейл2 CustomMembers)

        // *** End programmer edit section *** (Детейл2 CustomMembers)

        
        /// <summary>
        /// prop2.
        /// </summary>
        // *** Start programmer edit section *** (Детейл2.prop2 CustomAttributes)

        // *** End programmer edit section *** (Детейл2.prop2 CustomAttributes)
        [StrLen(255)]
        public virtual string prop2
        {
            get
            {
                // *** Start programmer edit section *** (Детейл2.prop2 Get start)

                // *** End programmer edit section *** (Детейл2.prop2 Get start)
                string result = this.fprop2;
                // *** Start programmer edit section *** (Детейл2.prop2 Get end)

                // *** End programmer edit section *** (Детейл2.prop2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Детейл2.prop2 Set start)

                // *** End programmer edit section *** (Детейл2.prop2 Set start)
                this.fprop2 = value;
                // *** Start programmer edit section *** (Детейл2.prop2 Set end)

                // *** End programmer edit section *** (Детейл2.prop2 Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.Flexberry.ORM.ODataService.Tests.Детейл.
        /// </summary>
        // *** Start programmer edit section *** (Детейл2.Детейл CustomAttributes)

        // *** End programmer edit section *** (Детейл2.Детейл CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage("Детейл")]
        [TypeUsage(new string[] {
                "NewPlatform.Flexberry.ORM.ODataService.Tests.Детейл",
                "NewPlatform.Flexberry.ORM.ODataService.Tests.ДетейлНаследник"})]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.Детейл Детейл
        {
            get
            {
                // *** Start programmer edit section *** (Детейл2.Детейл Get start)

                // *** End programmer edit section *** (Детейл2.Детейл Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.Детейл result = this.fДетейл;
                // *** Start programmer edit section *** (Детейл2.Детейл Get end)

                // *** End programmer edit section *** (Детейл2.Детейл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Детейл2.Детейл Set start)

                // *** End programmer edit section *** (Детейл2.Детейл Set start)
                this.fДетейл = value;
                // *** Start programmer edit section *** (Детейл2.Детейл Set end)

                // *** End programmer edit section *** (Детейл2.Детейл Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of Детейл2.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfДетейл2 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfДетейл2 CustomAttributes)
    public class DetailArrayOfДетейл2 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfДетейл2 members)

        // *** End programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfДетейл2 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Детейл2 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Детейл2.
        /// </summary>
        public DetailArrayOfДетейл2(NewPlatform.Flexberry.ORM.ODataService.Tests.Детейл fДетейл) : 
                base(typeof(Детейл2), ((ICSSoft.STORMNET.DataObject)(fДетейл)))
        {
        }
        
        public NewPlatform.Flexberry.ORM.ODataService.Tests.Детейл2 this[int index]
        {
            get
            {
                return ((NewPlatform.Flexberry.ORM.ODataService.Tests.Детейл2)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.Flexberry.ORM.ODataService.Tests.Детейл2 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
