//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ДочернийКласс.
    /// </summary>
    // *** Start programmer edit section *** (ДочернийКласс CustomAttributes)
    [ClassStorage("ДочернийКласс")]
    // *** End programmer edit section *** (ДочернийКласс CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДочернийКлассE", new string[] {
            "ChildProperty",
            "PropertyEnum",
            "PropertyBool",
            "PropertyInt",
            "PropertyDateTime",
            "PropertyString",
            "PropertyFloat",
            "PropertyDouble",
            "PropertyDecimal",
            "PropertySystemNullableDateTime",
            "PropertySystemNullableInt",
            "PropertySystemNullableGuid",
            "PropertySystemNullableDecimal",
            "PropertyStormnetNullableDateTime",
            "PropertyStormnetNullableInt",
            "PropertyStormnetKeyGuid",
            "PropertyStormnetNullableDecimal",
            "PropertyStormnetPartliedDate",
            "PropertyStormnetContact",
            "PropertyStormnetBlob",
            "PropertyStormnetEvent",
            "PropertyStormnetGeoData",
            "PropertyStormnetImage",
            "PropertyStormnetWebFile",
            "PropertyStormnetFile"})]
    public class ДочернийКласс : NewPlatform.Flexberry.ORM.ODataService.Tests.КлассСМножествомТипов
    {
        
        private string fChildProperty;
        
        // *** Start programmer edit section *** (ДочернийКласс CustomMembers)

        // *** End programmer edit section *** (ДочернийКласс CustomMembers)

        
        /// <summary>
        /// ChildProperty.
        /// </summary>
        // *** Start programmer edit section *** (ДочернийКласс.ChildProperty CustomAttributes)

        // *** End programmer edit section *** (ДочернийКласс.ChildProperty CustomAttributes)
        [StrLen(255)]
        public virtual string ChildProperty
        {
            get
            {
                // *** Start programmer edit section *** (ДочернийКласс.ChildProperty Get start)

                // *** End programmer edit section *** (ДочернийКласс.ChildProperty Get start)
                string result = this.fChildProperty;
                // *** Start programmer edit section *** (ДочернийКласс.ChildProperty Get end)

                // *** End programmer edit section *** (ДочернийКласс.ChildProperty Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДочернийКласс.ChildProperty Set start)

                // *** End programmer edit section *** (ДочернийКласс.ChildProperty Set start)
                this.fChildProperty = value;
                // *** Start programmer edit section *** (ДочернийКласс.ChildProperty Set end)

                // *** End programmer edit section *** (ДочернийКласс.ChildProperty Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДочернийКлассE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДочернийКлассE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДочернийКлассE", typeof(NewPlatform.Flexberry.ORM.ODataService.Tests.ДочернийКласс));
                }
            }
        }
    }
}
