//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Журнал.
    /// </summary>
    // *** Start programmer edit section *** (Журнал CustomAttributes)

    // *** End programmer edit section *** (Журнал CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Dжурнал", new string[] {
            "Название as \'Название\'",
            "Номер as \'Номер\'",
            "Автор2 as \'Автор\'"})]
    [MasterViewDefineAttribute("Dжурнал", "Автор2", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Имя")]
    public class Журнал : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private int fНомер;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.Автор fАвтор2;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.Библиотека fБиблиотека2;
        
        // *** Start programmer edit section *** (Журнал CustomMembers)

        // *** End programmer edit section *** (Журнал CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Журнал.Название CustomAttributes)

        // *** End programmer edit section *** (Журнал.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Журнал.Название Get start)

                // *** End programmer edit section *** (Журнал.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Журнал.Название Get end)

                // *** End programmer edit section *** (Журнал.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Журнал.Название Set start)

                // *** End programmer edit section *** (Журнал.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Журнал.Название Set end)

                // *** End programmer edit section *** (Журнал.Название Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Журнал.Номер CustomAttributes)

        // *** End programmer edit section *** (Журнал.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Журнал.Номер Get start)

                // *** End programmer edit section *** (Журнал.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Журнал.Номер Get end)

                // *** End programmer edit section *** (Журнал.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Журнал.Номер Set start)

                // *** End programmer edit section *** (Журнал.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Журнал.Номер Set end)

                // *** End programmer edit section *** (Журнал.Номер Set end)
            }
        }
        
        /// <summary>
        /// Журнал.
        /// </summary>
        // *** Start programmer edit section *** (Журнал.Автор2 CustomAttributes)

        // *** End programmer edit section *** (Журнал.Автор2 CustomAttributes)
        [PropertyStorage(new string[] {
                "Автор2"})]
        [NotNull()]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.Автор Автор2
        {
            get
            {
                // *** Start programmer edit section *** (Журнал.Автор2 Get start)

                // *** End programmer edit section *** (Журнал.Автор2 Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.Автор result = this.fАвтор2;
                // *** Start programmer edit section *** (Журнал.Автор2 Get end)

                // *** End programmer edit section *** (Журнал.Автор2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Журнал.Автор2 Set start)

                // *** End programmer edit section *** (Журнал.Автор2 Set start)
                this.fАвтор2 = value;
                // *** Start programmer edit section *** (Журнал.Автор2 Set end)

                // *** End programmer edit section *** (Журнал.Автор2 Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.Flexberry.ORM.ODataService.Tests.Библиотека.
        /// </summary>
        // *** Start programmer edit section *** (Журнал.Библиотека2 CustomAttributes)

        // *** End programmer edit section *** (Журнал.Библиотека2 CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Библиотека2"})]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.Библиотека Библиотека2
        {
            get
            {
                // *** Start programmer edit section *** (Журнал.Библиотека2 Get start)

                // *** End programmer edit section *** (Журнал.Библиотека2 Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.Библиотека result = this.fБиблиотека2;
                // *** Start programmer edit section *** (Журнал.Библиотека2 Get end)

                // *** End programmer edit section *** (Журнал.Библиотека2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Журнал.Библиотека2 Set start)

                // *** End programmer edit section *** (Журнал.Библиотека2 Set start)
                this.fБиблиотека2 = value;
                // *** Start programmer edit section *** (Журнал.Библиотека2 Set end)

                // *** End programmer edit section *** (Журнал.Библиотека2 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Dжурнал" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Dжурнал
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Dжурнал", typeof(NewPlatform.Flexberry.ORM.ODataService.Tests.Журнал));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Журнал.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЖурнал CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЖурнал CustomAttributes)
    public class DetailArrayOfЖурнал : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfЖурнал members)

        // *** End programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfЖурнал members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Журнал by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Журнал.
        /// </summary>
        public DetailArrayOfЖурнал(NewPlatform.Flexberry.ORM.ODataService.Tests.Библиотека fБиблиотека) : 
                base(typeof(Журнал), ((ICSSoft.STORMNET.DataObject)(fБиблиотека)))
        {
        }
        
        public NewPlatform.Flexberry.ORM.ODataService.Tests.Журнал this[int index]
        {
            get
            {
                return ((NewPlatform.Flexberry.ORM.ODataService.Tests.Журнал)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.Flexberry.ORM.ODataService.Tests.Журнал dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
