//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// КлассСоСтроковымКлючом.
    /// </summary>
    // *** Start programmer edit section *** (КлассСоСтроковымКлючом CustomAttributes)
    [KeyGenerator(typeof(GUIDToStringGenerator))]
    // *** End programmer edit section *** (КлассСоСтроковымКлючом CustomAttributes)
    [ClassStorage("КлассСоСтрокКл")]
    [PrimaryKeyStorage("StoragePrimaryKey")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class КлассСоСтроковымКлючом : ICSSoft.STORMNET.DataObject
    {
        
        private string fStoragePrimaryKey;
        
        // *** Start programmer edit section *** (КлассСоСтроковымКлючом CustomMembers)
        /// <summary>
        /// Gets or sets __PrimaryKey.
        /// </summary>
        public override object __PrimaryKey
        {
            get
            {
                return base.__PrimaryKey;
            }

            set
            {
                if ((string)value != string.Empty)
                {
                    base.__PrimaryKey = value;
                }
            }
        }
        // *** End programmer edit section *** (КлассСоСтроковымКлючом CustomMembers)

        
        /// <summary>
        /// StoragePrimaryKey.
        /// </summary>
        // *** Start programmer edit section *** (КлассСоСтроковымКлючом.StoragePrimaryKey CustomAttributes)

        // *** End programmer edit section *** (КлассСоСтроковымКлючом.StoragePrimaryKey CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string StoragePrimaryKey
        {
            get
            {
                // *** Start programmer edit section *** (КлассСоСтроковымКлючом.StoragePrimaryKey Get start)

                // *** End programmer edit section *** (КлассСоСтроковымКлючом.StoragePrimaryKey Get start)
                string result = this.fStoragePrimaryKey;
                // *** Start programmer edit section *** (КлассСоСтроковымКлючом.StoragePrimaryKey Get end)

                // *** End programmer edit section *** (КлассСоСтроковымКлючом.StoragePrimaryKey Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСоСтроковымКлючом.StoragePrimaryKey Set start)

                // *** End programmer edit section *** (КлассСоСтроковымКлючом.StoragePrimaryKey Set start)
                this.fStoragePrimaryKey = value;
                // *** Start programmer edit section *** (КлассСоСтроковымКлючом.StoragePrimaryKey Set end)

                // *** End programmer edit section *** (КлассСоСтроковымКлючом.StoragePrimaryKey Set end)
            }
        }
    }
}
