//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// КлассStoredDerived.
    /// </summary>
    // *** Start programmer edit section *** (КлассStoredDerived CustomAttributes)

    // *** End programmer edit section *** (КлассStoredDerived CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлассStoredDerivedE", new string[] {
            "StrAttr2",
            "StrAttr"})]
    public class КлассStoredDerived : NewPlatform.Flexberry.ORM.ODataService.Tests.КлассNotStored
    {
        
        private string fStrAttr2;
        
        // *** Start programmer edit section *** (КлассStoredDerived CustomMembers)

        // *** End programmer edit section *** (КлассStoredDerived CustomMembers)

        
        /// <summary>
        /// StrAttr2.
        /// </summary>
        // *** Start programmer edit section *** (КлассStoredDerived.StrAttr2 CustomAttributes)

        // *** End programmer edit section *** (КлассStoredDerived.StrAttr2 CustomAttributes)
        [StrLen(255)]
        public virtual string StrAttr2
        {
            get
            {
                // *** Start programmer edit section *** (КлассStoredDerived.StrAttr2 Get start)

                // *** End programmer edit section *** (КлассStoredDerived.StrAttr2 Get start)
                string result = this.fStrAttr2;
                // *** Start programmer edit section *** (КлассStoredDerived.StrAttr2 Get end)

                // *** End programmer edit section *** (КлассStoredDerived.StrAttr2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассStoredDerived.StrAttr2 Set start)

                // *** End programmer edit section *** (КлассStoredDerived.StrAttr2 Set start)
                this.fStrAttr2 = value;
                // *** Start programmer edit section *** (КлассStoredDerived.StrAttr2 Set end)

                // *** End programmer edit section *** (КлассStoredDerived.StrAttr2 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлассStoredDerivedE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлассStoredDerivedE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлассStoredDerivedE", typeof(NewPlatform.Flexberry.ORM.ODataService.Tests.КлассStoredDerived));
                }
            }
        }
    }
}
