//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// КлассСМножествомТипов.
    /// </summary>
    // *** Start programmer edit section *** (КлассСМножествомТипов CustomAttributes)

    // *** End programmer edit section *** (КлассСМножествомТипов CustomAttributes)
    [ClassStorage("КлассСМножТипов")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлассСМножествомТиповE", new string[] {
            "PropertyEnum",
            "PropertyBool",
            "PropertyInt",
            "PropertyDateTime",
            "PropertyString",
            "PropertyFloat",
            "PropertyDouble",
            "PropertyDecimal",
            "PropertySystemNullableDateTime",
            "PropertySystemNullableInt",
            "PropertySystemNullableGuid",
            "PropertySystemNullableDecimal",
            "PropertyStormnetNullableDateTime",
            "PropertyStormnetNullableInt",
            "PropertyStormnetKeyGuid",
            "PropertyStormnetNullableDecimal",
            "PropertyStormnetPartliedDate",
            "PropertyStormnetContact",
            "PropertyStormnetBlob",
            "PropertyStormnetEvent",
            "PropertyStormnetGeoData",
            "PropertyStormnetImage",
            "PropertyStormnetWebFile",
            "PropertyStormnetFile",
            "PropertyGeography"})]
    public class КлассСМножествомТипов : ICSSoft.STORMNET.DataObject
    {
        
        private Microsoft.Spatial.Geography fPropertyGeography;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.Цифра fPropertyEnum;
        
        private bool fPropertyBool;
        
        private int fPropertyInt;
        
        private System.DateTime fPropertyDateTime;
        
        private string fPropertyString;
        
        private float fPropertyFloat;
        
        private double fPropertyDouble;
        
        private decimal fPropertyDecimal;
        
        private System.Nullable<System.DateTime> fPropertySystemNullableDateTime;
        
        private System.Nullable<System.Int32> fPropertySystemNullableInt;
        
        private System.Nullable<System.Guid> fPropertySystemNullableGuid;
        
        private System.Nullable<System.Decimal> fPropertySystemNullableDecimal;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fPropertyStormnetNullableDateTime;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableInt fPropertyStormnetNullableInt;
        
        private ICSSoft.STORMNET.KeyGen.KeyGuid fPropertyStormnetKeyGuid;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDecimal fPropertyStormnetNullableDecimal;
        
        private ICSSoft.STORMNET.UserDataTypes.PartliedDate fPropertyStormnetPartliedDate;
        
        private ICSSoft.STORMNET.UserDataTypes.Contact fPropertyStormnetContact;
        
        private ICSSoft.STORMNET.UserDataTypes.Blob fPropertyStormnetBlob;
        
        private ICSSoft.STORMNET.UserDataTypes.Event fPropertyStormnetEvent;
        
        private ICSSoft.STORMNET.UserDataTypes.GeoData fPropertyStormnetGeoData;
        
        private ICSSoft.STORMNET.UserDataTypes.Image fPropertyStormnetImage;
        
        private ICSSoft.STORMNET.UserDataTypes.WebFile fPropertyStormnetWebFile;
        
        private ICSSoft.STORMNET.FileType.File fPropertyStormnetFile;
        
        // *** Start programmer edit section *** (КлассСМножествомТипов CustomMembers)

        // *** End programmer edit section *** (КлассСМножествомТипов CustomMembers)

        
        /// <summary>
        /// PropertyGeography.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyGeography CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertyGeography CustomAttributes)
        public virtual Microsoft.Spatial.Geography PropertyGeography
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyGeography Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyGeography Get start)
                Microsoft.Spatial.Geography result = this.fPropertyGeography;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyGeography Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyGeography Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyGeography Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyGeography Set start)
                this.fPropertyGeography = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyGeography Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyGeography Set end)
            }
        }
        
        /// <summary>
        /// PropertyEnum.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyEnum CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertyEnum CustomAttributes)
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.Цифра PropertyEnum
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyEnum Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyEnum Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.Цифра result = this.fPropertyEnum;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyEnum Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyEnum Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyEnum Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyEnum Set start)
                this.fPropertyEnum = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyEnum Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyEnum Set end)
            }
        }
        
        /// <summary>
        /// PropertyBool.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyBool CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertyBool CustomAttributes)
        public virtual bool PropertyBool
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyBool Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyBool Get start)
                bool result = this.fPropertyBool;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyBool Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyBool Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyBool Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyBool Set start)
                this.fPropertyBool = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyBool Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyBool Set end)
            }
        }
        
        /// <summary>
        /// PropertyInt.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyInt CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertyInt CustomAttributes)
        public virtual int PropertyInt
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyInt Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyInt Get start)
                int result = this.fPropertyInt;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyInt Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyInt Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyInt Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyInt Set start)
                this.fPropertyInt = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyInt Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyInt Set end)
            }
        }
        
        /// <summary>
        /// PropertyDateTime.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyDateTime CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertyDateTime CustomAttributes)
        public virtual System.DateTime PropertyDateTime
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyDateTime Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyDateTime Get start)
                System.DateTime result = this.fPropertyDateTime;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyDateTime Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyDateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyDateTime Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyDateTime Set start)
                this.fPropertyDateTime = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyDateTime Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyDateTime Set end)
            }
        }
        
        /// <summary>
        /// PropertyString.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyString CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertyString CustomAttributes)
        [StrLen(255)]
        public virtual string PropertyString
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyString Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyString Get start)
                string result = this.fPropertyString;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyString Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyString Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyString Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyString Set start)
                this.fPropertyString = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyString Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyString Set end)
            }
        }
        
        /// <summary>
        /// PropertyFloat.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyFloat CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertyFloat CustomAttributes)
        public virtual float PropertyFloat
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyFloat Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyFloat Get start)
                float result = this.fPropertyFloat;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyFloat Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyFloat Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyFloat Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyFloat Set start)
                this.fPropertyFloat = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyFloat Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyFloat Set end)
            }
        }
        
        /// <summary>
        /// PropertyDouble.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyDouble CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertyDouble CustomAttributes)
        public virtual double PropertyDouble
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyDouble Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyDouble Get start)
                double result = this.fPropertyDouble;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyDouble Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyDouble Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyDouble Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyDouble Set start)
                this.fPropertyDouble = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyDouble Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyDouble Set end)
            }
        }
        
        /// <summary>
        /// PropertyDecimal.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyDecimal CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertyDecimal CustomAttributes)
        public virtual decimal PropertyDecimal
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyDecimal Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyDecimal Get start)
                decimal result = this.fPropertyDecimal;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyDecimal Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyDecimal Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyDecimal Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyDecimal Set start)
                this.fPropertyDecimal = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyDecimal Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyDecimal Set end)
            }
        }
        
        /// <summary>
        /// PropertySystemNullableDateTime.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableDateTime CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableDateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> PropertySystemNullableDateTime
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableDateTime Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableDateTime Get start)
                System.Nullable<System.DateTime> result = this.fPropertySystemNullableDateTime;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableDateTime Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableDateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableDateTime Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableDateTime Set start)
                this.fPropertySystemNullableDateTime = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableDateTime Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableDateTime Set end)
            }
        }
        
        /// <summary>
        /// PropertySystemNullableInt.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableInt CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableInt CustomAttributes)
        public virtual System.Nullable<System.Int32> PropertySystemNullableInt
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableInt Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableInt Get start)
                System.Nullable<System.Int32> result = this.fPropertySystemNullableInt;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableInt Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableInt Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableInt Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableInt Set start)
                this.fPropertySystemNullableInt = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableInt Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableInt Set end)
            }
        }
        
        /// <summary>
        /// PropertySystemNullableGuid.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableGuid CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableGuid CustomAttributes)
        public virtual System.Nullable<System.Guid> PropertySystemNullableGuid
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableGuid Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableGuid Get start)
                System.Nullable<System.Guid> result = this.fPropertySystemNullableGuid;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableGuid Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableGuid Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableGuid Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableGuid Set start)
                this.fPropertySystemNullableGuid = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableGuid Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableGuid Set end)
            }
        }
        
        /// <summary>
        /// PropertySystemNullableDecimal.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableDecimal CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableDecimal CustomAttributes)
        public virtual System.Nullable<System.Decimal> PropertySystemNullableDecimal
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableDecimal Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableDecimal Get start)
                System.Nullable<System.Decimal> result = this.fPropertySystemNullableDecimal;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableDecimal Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableDecimal Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableDecimal Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableDecimal Set start)
                this.fPropertySystemNullableDecimal = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableDecimal Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertySystemNullableDecimal Set end)
            }
        }
        
        /// <summary>
        /// PropertyStormnetNullableDateTime.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableDateTime CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableDateTime CustomAttributes)
        [PropertyStorage("PropStormnetNullableDateTime")]
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime PropertyStormnetNullableDateTime
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableDateTime Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableDateTime Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fPropertyStormnetNullableDateTime;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableDateTime Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableDateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableDateTime Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableDateTime Set start)
                this.fPropertyStormnetNullableDateTime = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableDateTime Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableDateTime Set end)
            }
        }
        
        /// <summary>
        /// PropertyStormnetNullableInt.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableInt CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableInt CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableInt PropertyStormnetNullableInt
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableInt Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableInt Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableInt result = this.fPropertyStormnetNullableInt;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableInt Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableInt Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableInt Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableInt Set start)
                this.fPropertyStormnetNullableInt = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableInt Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableInt Set end)
            }
        }
        
        /// <summary>
        /// PropertyStormnetKeyGuid.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetKeyGuid CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetKeyGuid CustomAttributes)
        public virtual ICSSoft.STORMNET.KeyGen.KeyGuid PropertyStormnetKeyGuid
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetKeyGuid Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetKeyGuid Get start)
                ICSSoft.STORMNET.KeyGen.KeyGuid result = this.fPropertyStormnetKeyGuid;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetKeyGuid Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetKeyGuid Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetKeyGuid Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetKeyGuid Set start)
                this.fPropertyStormnetKeyGuid = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetKeyGuid Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetKeyGuid Set end)
            }
        }
        
        /// <summary>
        /// PropertyStormnetNullableDecimal.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableDecimal CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableDecimal CustomAttributes)
        [PropertyStorage("PropStormnetNullableDecimal")]
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDecimal PropertyStormnetNullableDecimal
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableDecimal Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableDecimal Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDecimal result = this.fPropertyStormnetNullableDecimal;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableDecimal Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableDecimal Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableDecimal Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableDecimal Set start)
                this.fPropertyStormnetNullableDecimal = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableDecimal Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetNullableDecimal Set end)
            }
        }
        
        /// <summary>
        /// PropertyStormnetPartliedDate.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetPartliedDate CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetPartliedDate CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.PartliedDate PropertyStormnetPartliedDate
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetPartliedDate Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetPartliedDate Get start)
                ICSSoft.STORMNET.UserDataTypes.PartliedDate result = this.fPropertyStormnetPartliedDate;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetPartliedDate Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetPartliedDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetPartliedDate Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetPartliedDate Set start)
                this.fPropertyStormnetPartliedDate = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetPartliedDate Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetPartliedDate Set end)
            }
        }
        
        /// <summary>
        /// PropertyStormnetContact.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetContact CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetContact CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.Contact PropertyStormnetContact
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetContact Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetContact Get start)
                ICSSoft.STORMNET.UserDataTypes.Contact result = this.fPropertyStormnetContact;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetContact Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetContact Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetContact Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetContact Set start)
                this.fPropertyStormnetContact = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetContact Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetContact Set end)
            }
        }
        
        /// <summary>
        /// PropertyStormnetBlob.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetBlob CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetBlob CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.Blob PropertyStormnetBlob
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetBlob Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetBlob Get start)
                ICSSoft.STORMNET.UserDataTypes.Blob result = this.fPropertyStormnetBlob;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetBlob Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetBlob Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetBlob Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetBlob Set start)
                this.fPropertyStormnetBlob = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetBlob Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetBlob Set end)
            }
        }
        
        /// <summary>
        /// PropertyStormnetEvent.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetEvent CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetEvent CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.Event PropertyStormnetEvent
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetEvent Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetEvent Get start)
                ICSSoft.STORMNET.UserDataTypes.Event result = this.fPropertyStormnetEvent;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetEvent Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetEvent Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetEvent Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetEvent Set start)
                this.fPropertyStormnetEvent = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetEvent Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetEvent Set end)
            }
        }
        
        /// <summary>
        /// PropertyStormnetGeoData.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetGeoData CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetGeoData CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.GeoData PropertyStormnetGeoData
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetGeoData Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetGeoData Get start)
                ICSSoft.STORMNET.UserDataTypes.GeoData result = this.fPropertyStormnetGeoData;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetGeoData Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetGeoData Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetGeoData Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetGeoData Set start)
                this.fPropertyStormnetGeoData = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetGeoData Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetGeoData Set end)
            }
        }
        
        /// <summary>
        /// PropertyStormnetImage.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetImage CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetImage CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.Image PropertyStormnetImage
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetImage Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetImage Get start)
                ICSSoft.STORMNET.UserDataTypes.Image result = this.fPropertyStormnetImage;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetImage Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetImage Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetImage Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetImage Set start)
                this.fPropertyStormnetImage = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetImage Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetImage Set end)
            }
        }
        
        /// <summary>
        /// PropertyStormnetWebFile.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetWebFile CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetWebFile CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.WebFile PropertyStormnetWebFile
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetWebFile Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetWebFile Get start)
                ICSSoft.STORMNET.UserDataTypes.WebFile result = this.fPropertyStormnetWebFile;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetWebFile Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetWebFile Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetWebFile Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetWebFile Set start)
                this.fPropertyStormnetWebFile = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetWebFile Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetWebFile Set end)
            }
        }
        
        /// <summary>
        /// PropertyStormnetFile.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetFile CustomAttributes)

        // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetFile CustomAttributes)
        public virtual ICSSoft.STORMNET.FileType.File PropertyStormnetFile
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetFile Get start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetFile Get start)
                ICSSoft.STORMNET.FileType.File result = this.fPropertyStormnetFile;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetFile Get end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetFile Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetFile Set start)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetFile Set start)
                this.fPropertyStormnetFile = value;
                // *** Start programmer edit section *** (КлассСМножествомТипов.PropertyStormnetFile Set end)

                // *** End programmer edit section *** (КлассСМножествомТипов.PropertyStormnetFile Set end)
            }
        }

        /// <summary>
        /// NotStoredProperty.
        /// </summary>
        // *** Start programmer edit section *** (КлассСМножествомТипов.NotStoredProperty CustomAttributes)
        [DataServiceExpression(typeof(ICSSoft.STORMNET.Business.SQLDataService), "@PropertyInt")]
        // *** End programmer edit section *** (КлассСМножествомТипов.NotStoredProperty CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        public virtual int NotStoredProperty
        {
            get
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.NotStoredProperty Get)

                return PropertyInt;
                // *** End programmer edit section *** (КлассСМножествомТипов.NotStoredProperty Get)
            }
            set
            {
                // *** Start programmer edit section *** (КлассСМножествомТипов.NotStoredProperty Set)
                PropertyInt = value;
                // *** End programmer edit section *** (КлассСМножествомТипов.NotStoredProperty Set)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлассСМножествомТиповE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлассСМножествомТиповE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлассСМножествомТиповE", typeof(NewPlatform.Flexberry.ORM.ODataService.Tests.КлассСМножествомТипов));
                }
            }
        }
    }
}
