//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Кошка.
    /// </summary>
    // *** Start programmer edit section *** (Кошка CustomAttributes)

    // *** End programmer edit section *** (Кошка CustomAttributes)
    [BusinessServer("NewPlatform.Flexberry.ORM.ODataService.Tests.CatsBS, NewPlatform.Flexberry.ORM.OD" +
        "ataService.Tests.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КошкаE", new string[] {
            "Кличка",
            "ДатаРождения",
            "Тип",
            "ПородаСтрокой",
            "Агрессивная",
            "КоличествоУсовСлева",
            "КоличествоУсовСправа",
            "КошкаСтрокой",
            "Порода.Название",
            "Порода.ТипПороды.Название"})]
    public class Кошка : ICSSoft.STORMNET.DataObject
    {
        
        private string fКличка;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fДатаРождения;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.ТипКошки fТип;
        
        private string fПородаСтрокой;
        
        private bool fАгрессивная;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableInt fКоличествоУсовСлева;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableInt fКоличествоУсовСправа;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.Порода fПорода;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfЛапа fЛапа;
        
        // *** Start programmer edit section *** (Кошка CustomMembers)

        // *** End programmer edit section *** (Кошка CustomMembers)

        
        /// <summary>
        /// Кличка.
        /// </summary>
        // *** Start programmer edit section *** (Кошка.Кличка CustomAttributes)

        // *** End programmer edit section *** (Кошка.Кличка CustomAttributes)
        [StrLen(255)]
        public virtual string Кличка
        {
            get
            {
                // *** Start programmer edit section *** (Кошка.Кличка Get start)

                // *** End programmer edit section *** (Кошка.Кличка Get start)
                string result = this.fКличка;
                // *** Start programmer edit section *** (Кошка.Кличка Get end)

                // *** End programmer edit section *** (Кошка.Кличка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кошка.Кличка Set start)

                // *** End programmer edit section *** (Кошка.Кличка Set start)
                this.fКличка = value;
                // *** Start programmer edit section *** (Кошка.Кличка Set end)

                // *** End programmer edit section *** (Кошка.Кличка Set end)
            }
        }
        
        /// <summary>
        /// ДатаРождения.
        /// </summary>
        // *** Start programmer edit section *** (Кошка.ДатаРождения CustomAttributes)

        // *** End programmer edit section *** (Кошка.ДатаРождения CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime ДатаРождения
        {
            get
            {
                // *** Start programmer edit section *** (Кошка.ДатаРождения Get start)

                // *** End programmer edit section *** (Кошка.ДатаРождения Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fДатаРождения;
                // *** Start programmer edit section *** (Кошка.ДатаРождения Get end)

                // *** End programmer edit section *** (Кошка.ДатаРождения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кошка.ДатаРождения Set start)

                // *** End programmer edit section *** (Кошка.ДатаРождения Set start)
                this.fДатаРождения = value;
                // *** Start programmer edit section *** (Кошка.ДатаРождения Set end)

                // *** End programmer edit section *** (Кошка.ДатаРождения Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (Кошка.Тип CustomAttributes)

        // *** End programmer edit section *** (Кошка.Тип CustomAttributes)
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.ТипКошки Тип
        {
            get
            {
                // *** Start programmer edit section *** (Кошка.Тип Get start)

                // *** End programmer edit section *** (Кошка.Тип Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.ТипКошки result = this.fТип;
                // *** Start programmer edit section *** (Кошка.Тип Get end)

                // *** End programmer edit section *** (Кошка.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кошка.Тип Set start)

                // *** End programmer edit section *** (Кошка.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (Кошка.Тип Set end)

                // *** End programmer edit section *** (Кошка.Тип Set end)
            }
        }
        
        /// <summary>
        /// ПородаСтрокой.
        /// </summary>
        // *** Start programmer edit section *** (Кошка.ПородаСтрокой CustomAttributes)

        // *** End programmer edit section *** (Кошка.ПородаСтрокой CustomAttributes)
        [StrLen(255)]
        public virtual string ПородаСтрокой
        {
            get
            {
                // *** Start programmer edit section *** (Кошка.ПородаСтрокой Get start)

                // *** End programmer edit section *** (Кошка.ПородаСтрокой Get start)
                string result = this.fПородаСтрокой;
                // *** Start programmer edit section *** (Кошка.ПородаСтрокой Get end)

                // *** End programmer edit section *** (Кошка.ПородаСтрокой Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кошка.ПородаСтрокой Set start)

                // *** End programmer edit section *** (Кошка.ПородаСтрокой Set start)
                this.fПородаСтрокой = value;
                // *** Start programmer edit section *** (Кошка.ПородаСтрокой Set end)

                // *** End programmer edit section *** (Кошка.ПородаСтрокой Set end)
            }
        }
        
        /// <summary>
        /// Агрессивная.
        /// </summary>
        // *** Start programmer edit section *** (Кошка.Агрессивная CustomAttributes)

        // *** End programmer edit section *** (Кошка.Агрессивная CustomAttributes)
        public virtual bool Агрессивная
        {
            get
            {
                // *** Start programmer edit section *** (Кошка.Агрессивная Get start)

                // *** End programmer edit section *** (Кошка.Агрессивная Get start)
                bool result = this.fАгрессивная;
                // *** Start programmer edit section *** (Кошка.Агрессивная Get end)

                // *** End programmer edit section *** (Кошка.Агрессивная Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кошка.Агрессивная Set start)

                // *** End programmer edit section *** (Кошка.Агрессивная Set start)
                this.fАгрессивная = value;
                // *** Start programmer edit section *** (Кошка.Агрессивная Set end)

                // *** End programmer edit section *** (Кошка.Агрессивная Set end)
            }
        }
        
        /// <summary>
        /// КоличествоУсовСлева.
        /// </summary>
        // *** Start programmer edit section *** (Кошка.КоличествоУсовСлева CustomAttributes)

        // *** End programmer edit section *** (Кошка.КоличествоУсовСлева CustomAttributes)
        [PropertyStorage("УсыСлева")]
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableInt КоличествоУсовСлева
        {
            get
            {
                // *** Start programmer edit section *** (Кошка.КоличествоУсовСлева Get start)

                // *** End programmer edit section *** (Кошка.КоличествоУсовСлева Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableInt result = this.fКоличествоУсовСлева;
                // *** Start programmer edit section *** (Кошка.КоличествоУсовСлева Get end)

                // *** End programmer edit section *** (Кошка.КоличествоУсовСлева Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кошка.КоличествоУсовСлева Set start)

                // *** End programmer edit section *** (Кошка.КоличествоУсовСлева Set start)
                this.fКоличествоУсовСлева = value;
                // *** Start programmer edit section *** (Кошка.КоличествоУсовСлева Set end)

                // *** End programmer edit section *** (Кошка.КоличествоУсовСлева Set end)
            }
        }
        
        /// <summary>
        /// КоличествоУсовСправа.
        /// </summary>
        // *** Start programmer edit section *** (Кошка.КоличествоУсовСправа CustomAttributes)

        // *** End programmer edit section *** (Кошка.КоличествоУсовСправа CustomAttributes)
        [PropertyStorage("УсыСправа")]
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableInt КоличествоУсовСправа
        {
            get
            {
                // *** Start programmer edit section *** (Кошка.КоличествоУсовСправа Get start)

                // *** End programmer edit section *** (Кошка.КоличествоУсовСправа Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableInt result = this.fКоличествоУсовСправа;
                // *** Start programmer edit section *** (Кошка.КоличествоУсовСправа Get end)

                // *** End programmer edit section *** (Кошка.КоличествоУсовСправа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кошка.КоличествоУсовСправа Set start)

                // *** End programmer edit section *** (Кошка.КоличествоУсовСправа Set start)
                this.fКоличествоУсовСправа = value;
                // *** Start programmer edit section *** (Кошка.КоличествоУсовСправа Set end)

                // *** End programmer edit section *** (Кошка.КоличествоУсовСправа Set end)
            }
        }
        
        /// <summary>
        /// КошкаСтрокой.
        /// </summary>
        // *** Start programmer edit section *** (Кошка.КошкаСтрокой CustomAttributes)

        // *** End programmer edit section *** (Кошка.КошкаСтрокой CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        [StrLen(255)]
        public virtual string КошкаСтрокой
        {
            get
            {
                // *** Start programmer edit section *** (Кошка.КошкаСтрокой Get)
                return null;
                // *** End programmer edit section *** (Кошка.КошкаСтрокой Get)
            }
            set
            {
                // *** Start programmer edit section *** (Кошка.КошкаСтрокой Set)

                // *** End programmer edit section *** (Кошка.КошкаСтрокой Set)
            }
        }
        
        /// <summary>
        /// Кошка.
        /// </summary>
        // *** Start programmer edit section *** (Кошка.Порода CustomAttributes)

        // *** End programmer edit section *** (Кошка.Порода CustomAttributes)
        [NotNull()]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.Порода Порода
        {
            get
            {
                // *** Start programmer edit section *** (Кошка.Порода Get start)

                // *** End programmer edit section *** (Кошка.Порода Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.Порода result = this.fПорода;
                // *** Start programmer edit section *** (Кошка.Порода Get end)

                // *** End programmer edit section *** (Кошка.Порода Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кошка.Порода Set start)

                // *** End programmer edit section *** (Кошка.Порода Set start)
                this.fПорода = value;
                // *** Start programmer edit section *** (Кошка.Порода Set end)

                // *** End programmer edit section *** (Кошка.Порода Set end)
            }
        }
        
        /// <summary>
        /// Кошка.
        /// </summary>
        // *** Start programmer edit section *** (Кошка.Лапа CustomAttributes)

        // *** End programmer edit section *** (Кошка.Лапа CustomAttributes)
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfЛапа Лапа
        {
            get
            {
                // *** Start programmer edit section *** (Кошка.Лапа Get start)

                // *** End programmer edit section *** (Кошка.Лапа Get start)
                if ((this.fЛапа == null))
                {
                    this.fЛапа = new NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfЛапа(this);
                }
                NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfЛапа result = this.fЛапа;
                // *** Start programmer edit section *** (Кошка.Лапа Get end)

                // *** End programmer edit section *** (Кошка.Лапа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кошка.Лапа Set start)

                // *** End programmer edit section *** (Кошка.Лапа Set start)
                this.fЛапа = value;
                // *** Start programmer edit section *** (Кошка.Лапа Set end)

                // *** End programmer edit section *** (Кошка.Лапа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КошкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КошкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КошкаE", typeof(NewPlatform.Flexberry.ORM.ODataService.Tests.Кошка));
                }
            }
        }
    }
}
