//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Лес.
    /// </summary>
    // *** Start programmer edit section *** (Лес CustomAttributes)

    // *** End programmer edit section *** (Лес CustomAttributes)
    [BusinessServer("NewPlatform.Flexberry.ORM.ODataService.Tests.ForestBS, NewPlatform.Flexberry.ORM." +
        "ODataService.Tests.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЛесE", new string[] {
            "Название as \'Название\'",
            "Площадь as \'Площадь\'",
            "Заповедник as \'Заповедник\'",
            "ДатаПоследнегоОсмотра as \'Дата последнего осмотра\'",
            "Страна as \'Страна\'",
            "Страна.Название as \'Название\'"})]
    [View("ЛесL", new string[] {
            "Название as \'Название\'",
            "Площадь as \'Площадь\'",
            "Заповедник as \'Заповедник\'",
            "ДатаПоследнегоОсмотра as \'Дата последнего осмотра\'",
            "Страна.Название as \'Название\'"})]
    public class Лес : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private int fПлощадь;
        
        private bool fЗаповедник;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fДатаПоследнегоОсмотра;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.Страна fСтрана;
        
        // *** Start programmer edit section *** (Лес CustomMembers)

        // *** End programmer edit section *** (Лес CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Лес.Название CustomAttributes)

        // *** End programmer edit section *** (Лес.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Лес.Название Get start)

                // *** End programmer edit section *** (Лес.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Лес.Название Get end)

                // *** End programmer edit section *** (Лес.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Лес.Название Set start)

                // *** End programmer edit section *** (Лес.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Лес.Название Set end)

                // *** End programmer edit section *** (Лес.Название Set end)
            }
        }
        
        /// <summary>
        /// Площадь.
        /// </summary>
        // *** Start programmer edit section *** (Лес.Площадь CustomAttributes)

        // *** End programmer edit section *** (Лес.Площадь CustomAttributes)
        public virtual int Площадь
        {
            get
            {
                // *** Start programmer edit section *** (Лес.Площадь Get start)

                // *** End programmer edit section *** (Лес.Площадь Get start)
                int result = this.fПлощадь;
                // *** Start programmer edit section *** (Лес.Площадь Get end)

                // *** End programmer edit section *** (Лес.Площадь Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Лес.Площадь Set start)

                // *** End programmer edit section *** (Лес.Площадь Set start)
                this.fПлощадь = value;
                // *** Start programmer edit section *** (Лес.Площадь Set end)

                // *** End programmer edit section *** (Лес.Площадь Set end)
            }
        }
        
        /// <summary>
        /// Заповедник.
        /// </summary>
        // *** Start programmer edit section *** (Лес.Заповедник CustomAttributes)

        // *** End programmer edit section *** (Лес.Заповедник CustomAttributes)
        public virtual bool Заповедник
        {
            get
            {
                // *** Start programmer edit section *** (Лес.Заповедник Get start)

                // *** End programmer edit section *** (Лес.Заповедник Get start)
                bool result = this.fЗаповедник;
                // *** Start programmer edit section *** (Лес.Заповедник Get end)

                // *** End programmer edit section *** (Лес.Заповедник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Лес.Заповедник Set start)

                // *** End programmer edit section *** (Лес.Заповедник Set start)
                this.fЗаповедник = value;
                // *** Start programmer edit section *** (Лес.Заповедник Set end)

                // *** End programmer edit section *** (Лес.Заповедник Set end)
            }
        }
        
        /// <summary>
        /// ДатаПоследнегоОсмотра.
        /// </summary>
        // *** Start programmer edit section *** (Лес.ДатаПоследнегоОсмотра CustomAttributes)

        // *** End programmer edit section *** (Лес.ДатаПоследнегоОсмотра CustomAttributes)
        [PropertyStorage("ДатаПослОсмотра")]
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime ДатаПоследнегоОсмотра
        {
            get
            {
                // *** Start programmer edit section *** (Лес.ДатаПоследнегоОсмотра Get start)

                // *** End programmer edit section *** (Лес.ДатаПоследнегоОсмотра Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fДатаПоследнегоОсмотра;
                // *** Start programmer edit section *** (Лес.ДатаПоследнегоОсмотра Get end)

                // *** End programmer edit section *** (Лес.ДатаПоследнегоОсмотра Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Лес.ДатаПоследнегоОсмотра Set start)

                // *** End programmer edit section *** (Лес.ДатаПоследнегоОсмотра Set start)
                this.fДатаПоследнегоОсмотра = value;
                // *** Start programmer edit section *** (Лес.ДатаПоследнегоОсмотра Set end)

                // *** End programmer edit section *** (Лес.ДатаПоследнегоОсмотра Set end)
            }
        }
        
        /// <summary>
        /// Лес.
        /// </summary>
        // *** Start programmer edit section *** (Лес.Страна CustomAttributes)

        // *** End programmer edit section *** (Лес.Страна CustomAttributes)
        [PropertyStorage(new string[] {
                "Страна"})]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.Страна Страна
        {
            get
            {
                // *** Start programmer edit section *** (Лес.Страна Get start)

                // *** End programmer edit section *** (Лес.Страна Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.Страна result = this.fСтрана;
                // *** Start programmer edit section *** (Лес.Страна Get end)

                // *** End programmer edit section *** (Лес.Страна Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Лес.Страна Set start)

                // *** End programmer edit section *** (Лес.Страна Set start)
                this.fСтрана = value;
                // *** Start programmer edit section *** (Лес.Страна Set end)

                // *** End programmer edit section *** (Лес.Страна Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЛесE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЛесE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЛесE", typeof(NewPlatform.Flexberry.ORM.ODataService.Tests.Лес));
                }
            }
            
            /// <summary>
            /// "ЛесL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЛесL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЛесL", typeof(NewPlatform.Flexberry.ORM.ODataService.Tests.Лес));
                }
            }
        }
    }
}
