//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Мастер.
    /// </summary>
    // *** Start programmer edit section *** (Мастер CustomAttributes)
    [PublishName("NewPlatform.Flexberry.ORM.ODataService.Tests.MasterAlias", "MasterAliases")]
    // *** End programmer edit section *** (Мастер CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Мастер : ICSSoft.STORMNET.DataObject
    {
        
        private string fprop;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.Мастер2 fМастер2;
        
        // *** Start programmer edit section *** (Мастер CustomMembers)

        // *** End programmer edit section *** (Мастер CustomMembers)

        
        /// <summary>
        /// prop.
        /// </summary>
        // *** Start programmer edit section *** (Мастер.prop CustomAttributes)
        
        // *** End programmer edit section *** (Мастер.prop CustomAttributes)
        [StrLen(255)]
        public virtual string prop
        {
            get
            {
                // *** Start programmer edit section *** (Мастер.prop Get start)

                // *** End programmer edit section *** (Мастер.prop Get start)
                string result = this.fprop;
                // *** Start programmer edit section *** (Мастер.prop Get end)

                // *** End programmer edit section *** (Мастер.prop Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Мастер.prop Set start)

                // *** End programmer edit section *** (Мастер.prop Set start)
                this.fprop = value;
                // *** Start programmer edit section *** (Мастер.prop Set end)

                // *** End programmer edit section *** (Мастер.prop Set end)
            }
        }
        
        /// <summary>
        /// Мастер.
        /// </summary>
        // *** Start programmer edit section *** (Мастер.Мастер2 CustomAttributes)
        [PublishName("Master2Alias")]
        // *** End programmer edit section *** (Мастер.Мастер2 CustomAttributes)
        [PropertyStorage(new string[] {
                "Мастер2"})]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.Мастер2 Мастер2
        {
            get
            {
                // *** Start programmer edit section *** (Мастер.Мастер2 Get start)

                // *** End programmer edit section *** (Мастер.Мастер2 Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.Мастер2 result = this.fМастер2;
                // *** Start programmer edit section *** (Мастер.Мастер2 Get end)

                // *** End programmer edit section *** (Мастер.Мастер2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Мастер.Мастер2 Set start)

                // *** End programmer edit section *** (Мастер.Мастер2 Set start)
                this.fМастер2 = value;
                // *** Start programmer edit section *** (Мастер.Мастер2 Set end)

                // *** End programmer edit section *** (Мастер.Мастер2 Set end)
            }
        }
    }
}
