//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Перелом.
    /// </summary>
    // *** Start programmer edit section *** (Перелом CustomAttributes)

    // *** End programmer edit section *** (Перелом CustomAttributes)
    [BusinessServer("NewPlatform.Flexberry.ORM.ODataService.Tests.CatsBS, NewPlatform.Flexberry.ORM.OD" +
        "ataService.Tests.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Перелом : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.ТипПерелома fТип;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.Лапа fЛапа;
        
        // *** Start programmer edit section *** (Перелом CustomMembers)

        // *** End programmer edit section *** (Перелом CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Перелом.Дата CustomAttributes)

        // *** End programmer edit section *** (Перелом.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Перелом.Дата Get start)

                // *** End programmer edit section *** (Перелом.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Перелом.Дата Get end)

                // *** End programmer edit section *** (Перелом.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Перелом.Дата Set start)

                // *** End programmer edit section *** (Перелом.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Перелом.Дата Set end)

                // *** End programmer edit section *** (Перелом.Дата Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (Перелом.Тип CustomAttributes)

        // *** End programmer edit section *** (Перелом.Тип CustomAttributes)
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.ТипПерелома Тип
        {
            get
            {
                // *** Start programmer edit section *** (Перелом.Тип Get start)

                // *** End programmer edit section *** (Перелом.Тип Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.ТипПерелома result = this.fТип;
                // *** Start programmer edit section *** (Перелом.Тип Get end)

                // *** End programmer edit section *** (Перелом.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Перелом.Тип Set start)

                // *** End programmer edit section *** (Перелом.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (Перелом.Тип Set end)

                // *** End programmer edit section *** (Перелом.Тип Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.Flexberry.ORM.ODataService.Tests.Лапа.
        /// </summary>
        // *** Start programmer edit section *** (Перелом.Лапа CustomAttributes)

        // *** End programmer edit section *** (Перелом.Лапа CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.Лапа Лапа
        {
            get
            {
                // *** Start programmer edit section *** (Перелом.Лапа Get start)

                // *** End programmer edit section *** (Перелом.Лапа Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.Лапа result = this.fЛапа;
                // *** Start programmer edit section *** (Перелом.Лапа Get end)

                // *** End programmer edit section *** (Перелом.Лапа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Перелом.Лапа Set start)

                // *** End programmer edit section *** (Перелом.Лапа Set start)
                this.fЛапа = value;
                // *** Start programmer edit section *** (Перелом.Лапа Set end)

                // *** End programmer edit section *** (Перелом.Лапа Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of Перелом.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfПерелом CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfПерелом CustomAttributes)
    public class DetailArrayOfПерелом : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfПерелом members)

        // *** End programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfПерелом members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Перелом by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Перелом.
        /// </summary>
        public DetailArrayOfПерелом(NewPlatform.Flexberry.ORM.ODataService.Tests.Лапа fЛапа) : 
                base(typeof(Перелом), ((ICSSoft.STORMNET.DataObject)(fЛапа)))
        {
        }
        
        public NewPlatform.Flexberry.ORM.ODataService.Tests.Перелом this[int index]
        {
            get
            {
                return ((NewPlatform.Flexberry.ORM.ODataService.Tests.Перелом)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.Flexberry.ORM.ODataService.Tests.Перелом dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
