//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Порода.
    /// </summary>
    // *** Start programmer edit section *** (Порода CustomAttributes)

    // *** End programmer edit section *** (Порода CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Порода : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.ТипПороды fТипПороды;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.Порода fИерархия;
        
        // *** Start programmer edit section *** (Порода CustomMembers)

        // *** End programmer edit section *** (Порода CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Порода.Название CustomAttributes)

        // *** End programmer edit section *** (Порода.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Порода.Название Get start)

                // *** End programmer edit section *** (Порода.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Порода.Название Get end)

                // *** End programmer edit section *** (Порода.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Порода.Название Set start)

                // *** End programmer edit section *** (Порода.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Порода.Название Set end)

                // *** End programmer edit section *** (Порода.Название Set end)
            }
        }
        
        /// <summary>
        /// Порода.
        /// </summary>
        // *** Start programmer edit section *** (Порода.ТипПороды CustomAttributes)

        // *** End programmer edit section *** (Порода.ТипПороды CustomAttributes)
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.ТипПороды ТипПороды
        {
            get
            {
                // *** Start programmer edit section *** (Порода.ТипПороды Get start)

                // *** End programmer edit section *** (Порода.ТипПороды Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.ТипПороды result = this.fТипПороды;
                // *** Start programmer edit section *** (Порода.ТипПороды Get end)

                // *** End programmer edit section *** (Порода.ТипПороды Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Порода.ТипПороды Set start)

                // *** End programmer edit section *** (Порода.ТипПороды Set start)
                this.fТипПороды = value;
                // *** Start programmer edit section *** (Порода.ТипПороды Set end)

                // *** End programmer edit section *** (Порода.ТипПороды Set end)
            }
        }
        
        /// <summary>
        /// Порода.
        /// </summary>
        // *** Start programmer edit section *** (Порода.Иерархия CustomAttributes)

        // *** End programmer edit section *** (Порода.Иерархия CustomAttributes)
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.Порода Иерархия
        {
            get
            {
                // *** Start programmer edit section *** (Порода.Иерархия Get start)

                // *** End programmer edit section *** (Порода.Иерархия Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.Порода result = this.fИерархия;
                // *** Start programmer edit section *** (Порода.Иерархия Get end)

                // *** End programmer edit section *** (Порода.Иерархия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Порода.Иерархия Set start)

                // *** End programmer edit section *** (Порода.Иерархия Set start)
                this.fИерархия = value;
                // *** Start programmer edit section *** (Порода.Иерархия Set end)

                // *** End programmer edit section *** (Порода.Иерархия Set end)
            }
        }
    }
}
