//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Страна.
    /// </summary>
    // *** Start programmer edit section *** (Страна CustomAttributes)

    // *** End programmer edit section *** (Страна CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СтранаE", new string[] {
            "Название as \'Название\'"})]
    [View("СтранаL", new string[] {
            "Название as \'Название\'"})]
    public class Страна : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        // *** Start programmer edit section *** (Страна CustomMembers)

        // *** End programmer edit section *** (Страна CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Страна.Название CustomAttributes)

        // *** End programmer edit section *** (Страна.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Страна.Название Get start)

                // *** End programmer edit section *** (Страна.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Страна.Название Get end)

                // *** End programmer edit section *** (Страна.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Страна.Название Set start)

                // *** End programmer edit section *** (Страна.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Страна.Название Set end)

                // *** End programmer edit section *** (Страна.Название Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СтранаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтранаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтранаE", typeof(NewPlatform.Flexberry.ORM.ODataService.Tests.Страна));
                }
            }
            
            /// <summary>
            /// "СтранаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтранаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтранаL", typeof(NewPlatform.Flexberry.ORM.ODataService.Tests.Страна));
                }
            }
        }
    }
}
