//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ТипПерелома.
    /// </summary>
    // *** Start programmer edit section *** (ТипПерелома CustomAttributes)

    // *** End programmer edit section *** (ТипПерелома CustomAttributes)
    public enum ТипПерелома
    {
        
        // *** Start programmer edit section *** (ТипПерелома.Открытый CustomAttributes)

        // *** End programmer edit section *** (ТипПерелома.Открытый CustomAttributes)
        Открытый,
        
        // *** Start programmer edit section *** (ТипПерелома.Закрытый CustomAttributes)

        // *** End programmer edit section *** (ТипПерелома.Закрытый CustomAttributes)
        Закрытый,
    }
}
