//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Цифра.
    /// </summary>
    // *** Start programmer edit section *** (Цифра CustomAttributes)

    // *** End programmer edit section *** (Цифра CustomAttributes)
    public enum Цифра
    {
        
        // *** Start programmer edit section *** (Цифра.Ноль CustomAttributes)

        // *** End programmer edit section *** (Цифра.Ноль CustomAttributes)
        Ноль,
        
        // *** Start programmer edit section *** (Цифра.Один CustomAttributes)

        // *** End programmer edit section *** (Цифра.Один CustomAttributes)
        Один,
        
        // *** Start programmer edit section *** (Цифра.Два CustomAttributes)

        // *** End programmer edit section *** (Цифра.Два CustomAttributes)
        Два,
        
        // *** Start programmer edit section *** (Цифра.Три CustomAttributes)

        // *** End programmer edit section *** (Цифра.Три CustomAttributes)
        Три,
        
        // *** Start programmer edit section *** (Цифра.Четыре CustomAttributes)

        // *** End programmer edit section *** (Цифра.Четыре CustomAttributes)
        Четыре,
        
        // *** Start programmer edit section *** (Цифра.Пять CustomAttributes)

        // *** End programmer edit section *** (Цифра.Пять CustomAttributes)
        Пять,
        
        // *** Start programmer edit section *** (Цифра.Шесть CustomAttributes)

        // *** End programmer edit section *** (Цифра.Шесть CustomAttributes)
        Шесть,
        
        // *** Start programmer edit section *** (Цифра.Семь CustomAttributes)

        // *** End programmer edit section *** (Цифра.Семь CustomAttributes)
        Семь,
        
        // *** Start programmer edit section *** (Цифра.Восемь CustomAttributes)

        // *** End programmer edit section *** (Цифра.Восемь CustomAttributes)
        Восемь,
        
        // *** Start programmer edit section *** (Цифра.Девять CustomAttributes)

        // *** End programmer edit section *** (Цифра.Девять CustomAttributes)
        Девять,
    }
}
