version: '2.2'

services:
  SrvHBDN:
    image: dh.ics.perm.ru/kaf/alt.p8-postgresql9.6-ru:${TAG}
    environment:
      - POSTGRES_max_connections=250
    ports:
      - 5432:5432
    volumes:
      - DB:/var/lib/pgsql/data/

  ApproveService:
    image: dh.ics.perm.ru/zs/approveservice:${TAG}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 51194:80

  template-collection:
    image: dh.ics.perm.ru/zs-dms-ose/template-collection:${TAG}
    # ports:
    #   - 56389:80
    volumes:
      - /home/ics/template-library:/var/template-library

  dms-back:
    image: dh.ics.perm.ru/zs-dms-ose/readycheck/dms-back:${TAG}
    depends_on:
      - SrvHBDN
    environment:
      - READYCHECK_URLS=SrvHBDN:5432
      - FILE_STORAGE_URL=${FILE_STORAGE_URL}
      - FILE_STORAGE_ROOT_DIRECTORY=${FILE_STORAGE_ROOT_DIRECTORY}
      - TEMPLATE_LIBRARY_URL=${TEMPLATE_LIBRARY_URL}
      - DMS_CONNECTION_STRING=${DMS_CONNECTION_STRING}
      - DMS_AUDIT_CONNECTION_STRING=${DMS_AUDIT_CONNECTION_STRING}
      - DOCUMENTS_FOR_REGISTRATION_SPECIALIST=${DOCUMENTS_FOR_REGISTRATION_SPECIALIST}
      - SHARED_KEYS_STORE_PATH=/var/sharedKeys
      - REPORT_SERVER_URL=${REPORT_SERVER_URL}
      - REPORT_SERVER_ACCOUNT=${REPORT_SERVER_ACCOUNT}
      - REPORT_SERVER_PASSWORD=${REPORT_SERVER_PASSWORD}
      - AUTHORITY_URL=${AUTHORITY_URL}
      - NAMED_COUNTER_SERVICE=${NAMED_COUNTER_SERVICE}
      - NAMED_COUNTER_SERVICE_PARAM_NAME=${NAMED_COUNTER_SERVICE_PARAM_NAME}
      - NAMED_COUNTER_SERVICE_PARAM_VALUE=${NAMED_COUNTER_SERVICE_PARAM_VALUE}
      - MAILING_LISTS_PATH=/var/sambaData/MailingLists
      - MAILING_LISTS_NETWORK_PATH=\\dms.zspk.perm.ru\Data\MailingLists\
      - GRAPHITE_URL=${GRAPHITE_URL}
      - DOCUMENT_MERGE_SVC_URL=http://dms.zspk.perm.ru:11180/api/DocumentMerge
      - METRICS_CONTEXT_NAME=DevTest.ODataBackend
      - LOGSTASH_HOST=${LOGSTASH_HOST}
      - LOGSTASH_PORT=${LOGSTASH_PORT}
      - AGENDAS_URL=${AGENDAS_URL}
      - AGENDAS_SERVICE_BUS_ADDRESS=${AGENDAS_SERVICE_BUS_ADDRESS}
      - DATA_SERVICE_TYPE=${DATA_SERVICE_TYPE}
      - HWSB_URL=${HWSB_URL}
      - ACT_CONSTRUCTOR_IMPORT_ENABLE=${ACT_CONSTRUCTOR_IMPORT_ENABLE_BACK}
      - AMENDMENT_IMPORT_ENABLE=${AMENDMENT_IMPORT_ENABLE_BACK}
      - CONSTRUCTOR_IMPORT_BY_BUTTON_ENABLE=${CONSTRUCTOR_IMPORT_BY_BUTTON_ENABLE}
      - CONSTRUCTOR_SENDER_HOSTNAME=${CONSTRUCTOR_SENDER_HOSTNAME}
      - CONSTRUCTOR_SENDER_USER=${CONSTRUCTOR_SENDER_USER}
      - CONSTRUCTOR_SENDER_PASSWORD=${CONSTRUCTOR_SENDER_PASSWORD}
    # ports:
    #   - 8183:80
    extra_hosts:
      - "dms.zspk.perm.ru:10.130.5.176"
      - "srvhshpoint:10.130.5.82"
      - "srvhnp-wf:10.130.5.79"
      - "srvhnp-app:10.130.5.77"
    volumes:
      - ZsDms_sharedData:/var/sharedKeys
      - ZsDms_SambaServerData:/var/sambaData

  bpm-activityservice:
    image: dh.ics.perm.ru/zs-dms-ose/readycheck/bpm-activityservice:${TAG}
    depends_on:
      - SrvHBDN
    environment:
      - READYCHECK_URLS=SrvHBDN:5432
      - BPM_API_URL=${BPM_API_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_MAIL_FROM=${SMTP_MAIL_FROM}
      - SMTP_LOGIN=${SMTP_LOGIN}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_ENABLE_SSL=${SMTP_ENABLE_SSL}
      - SMTP_CHECK_CERTIFICATE_REVOCATION=${SMTP_CHECK_CERTIFICATE_REVOCATION}
      - DMS_CONNECTION_STRING=${DMS_CONNECTION_STRING}
      - DMS_AUDIT_CONNECTION_STRING=${DMS_AUDIT_CONNECTION_STRING}
      - OMSU_URL=http://10.130.5.150:59000
      - REPORT_SERVER_URL=${REPORT_SERVER_URL}
      - REPORT_SERVER_ACCOUNT=${REPORT_SERVER_ACCOUNT}
      - REPORT_SERVER_PASSWORD=${REPORT_SERVER_PASSWORD}
      - NAMED_COUNTER_SERVICE=${NAMED_COUNTER_SERVICE}
      - NAMED_COUNTER_SERVICE_PARAM_NAME=${NAMED_COUNTER_SERVICE_PARAM_NAME}
      - NAMED_COUNTER_SERVICE_PARAM_VALUE=${NAMED_COUNTER_SERVICE_PARAM_VALUE}
      - FILE_STORAGE_URL=${FILE_STORAGE_URL}
      - FILE_STORAGE_ROOT_DIRECTORY=${FILE_STORAGE_ROOT_DIRECTORY}
      - AUTHORITY_URL=${AUTHORITY_URL}
      - GRAPHITE_URL=${GRAPHITE_URL}
      - METRICS_CONTEXT_NAME=DevTest.ActivityServices
      - TEMPLATE_LIBRARY_URL=${TEMPLATE_LIBRARY_URL}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
      - LOGSTASH_PORT=${LOGSTASH_PORT}
      - AGENDAS_URL=${AGENDAS_URL}
      - AGENDAS_SERVICE_BUS_ADDRESS=${AGENDAS_SERVICE_BUS_ADDRESS}
      - DATA_SERVICE_TYPE=${DATA_SERVICE_TYPE}
      - PRINT_COPY_SVC_URL=http://dms.zspk.perm.ru:11180/api/CreatePrintCopy
      - HWSB_URL=${HWSB_URL}
      - SYSTEM_ADMIN_EMAIL=Chaschina@pminst.ru,abelikova@pminst.ru,OMatvienko@pminst.ru,dronzhin@pminst.ru
      - ACT_CONSTRUCTOR_IMPORT_ENABLE=${ACT_CONSTRUCTOR_IMPORT_ENABLE_AS}
      - AMENDMENT_IMPORT_ENABLE=${AMENDMENT_IMPORT_ENABLE_AS}
      - CONSTRUCTOR_IMPORT_BY_BUTTON_ENABLE=${CONSTRUCTOR_IMPORT_BY_BUTTON_ENABLE}
      - CONSTRUCTOR_SENDER_HOSTNAME=${CONSTRUCTOR_SENDER_HOSTNAME}
      - CONSTRUCTOR_SENDER_USER=${CONSTRUCTOR_SENDER_USER}
      - CONSTRUCTOR_SENDER_PASSWORD=${CONSTRUCTOR_SENDER_PASSWORD}
    # ports:
    #   - 8182:80
    extra_hosts:
      - "dms.zspk.perm.ru:10.130.5.176"
      - "srvhshpoint:10.130.5.82"
      - "srvhnp-wf:10.130.5.79"
      - "srvhnp-app:10.130.5.77"
      - "mail.pminst.ru:10.130.6.30"

  bpm-timer:
    image: dh.ics.perm.ru/zs-dms-ose/readycheck/runtime-timer-quartznet-service:${TAG}
    depends_on:
      - SrvHBDN
    environment:
      - READYCHECK_URLS=SrvHBDN:5432
      - XMLTEMPLATES=./NewPlatform.Flexberry.BPM.Runtime.QuartzNetTimer.Service.exe.config
      - JBPM_API_URL=${JBPM_API_URL}
      - JBPM_REQUEST_TIMEOUT=80
      - HWSB_URL=${HWSB_URL}
      - BPM_CONNECTION_STRING=${BPM_CONNECTION_STRING}
      - DMS_CONNECTION_STRING=${DMS_CONNECTION_STRING}
      - QUARTZ_CONNECTION_STRING=Server=SrvHBDN;Port=5432;User Id=postgres;password=p@ssw0rd;Database=zsdms_quartznet;
      - LOGSTASH_HOST=${LOGSTASH_HOST}
      - LOGSTASH_PORT=${LOGSTASH_PORT}
    # ports:
    #   - 55555:55555
    volumes:
      - /etc/localtime:/etc/localtime
    extra_hosts:
      - "dms.zspk.perm.ru:10.130.5.176"

  bpm-webapi:
    image: dh.ics.perm.ru/zs-dms-ose/readycheck/web-api:${TAG}
    depends_on:
      - SrvHBDN
      - bpm-timer
    environment:
      - READYCHECK_URLS=SrvHBDN:5432 bpm-timer:55555
      - XMLTEMPLATES=/app/Web.config
      - ACTIVITY_SERVICES_API_URL=http://bpm-activityservice/activityservice
      - JBPM_API_URL=${JBPM_API_URL}
      - BPM_CONNECTION_STRING=${BPM_CONNECTION_STRING}
      - DMS_CONNECTION_STRING=${DMS_CONNECTION_STRING}
      - BPM_TIMER_URL=tcp://bpm-timer:55555/FlowpointFlexberryTimer
      - HWSB_URL=${HWSB_URL}
      - GRAPHITE_URL=${GRAPHITE_URL}
      - METRICS_CONTEXT_NAME=DevTest.BpmWebApi
      - LOGSTASH_HOST=${LOGSTASH_HOST}
      - LOGSTASH_PORT=${LOGSTASH_PORT}
    ports:
      - 6337:80
    extra_hosts:
      - "dms.zspk.perm.ru:10.130.5.176"
    volumes:
      - /etc/localtime:/etc/localtime

  front-nginx:
    image: dh.ics.perm.ru/zs-dms-ose/readycheck/dms-front:${TAG}
    depends_on:
      - dms-back
      - bpm-webapi
      - bpm-activityservice
      - WebDavServer
      - IdentityServer
      - template-collection
    environment:
      - READYCHECK_URLS=SrvHBDN:5432 http://IdentityServer http://WebDavServer http://dms-back http://bpm-activityservice http://bpm-activityservice http://template-collection
    ports:
      - 443:443
      - 80:80

  WebDavServer:
    image: dh.ics.perm.ru/zs/webdavserver:${TAG}
    ports:
      - 9400:80
    environment:
      - WEBDAV_pathBase=/webdav
      - WEBDAV_SharedKeysStorePath=/var/sharedKeys
      - WEBDAV_DMSODataBackendUri=https://dms.zspk.perm.ru
      - ASPNETCORE_ENVIRONMENT=Staging
    volumes:
      - ZsDms_WebDavServerFiles:/var/fileStore
      - ZsDms_sharedData:/var/sharedKeys
    extra_hosts:
      - "dms.zspk.perm.ru:10.130.5.176"

  IdentityServer:
    image: dh.ics.perm.ru/zs/identityserver:${TAG}
    ports:
      - 10080:80
      - 10443:443
    healthcheck:
      interval: 10s
      timeout: 5s
    environment:
      - IDENTITY_pathBase=/auth
      - IDENTITY_knownProxy=dms.zspk.perm.ru
      - IDENTITY_RootHostUrlList=http://localhost:4202,https://dms.zspk.perm.ru,https://10.130.5.176,https://acts.zspk.perm.ru
      - IDENTITY_DMSODataBackendUri=http://dms-back/
      - ASPNETCORE_ENVIRONMENT=Development
      - IDENTITY_SharedKeysStorePath=/var/sharedKeys
      - IDENTITY_IdentityServerLdap__Url=10.130.5.73
      - IDENTITY_HealthCheckLogin=testuser12
      - IDENTITY_HealthCheckPassword=testuser
    volumes:
      - ZsDms_sharedData:/var/sharedKeys
    extra_hosts:
      - "dms.zspk.perm.ru:10.130.5.176"
      - "acts.zspk.perm.ru:10.130.5.23"

  SambaServer:
    image: dperson/samba
    volumes:
      - ZsDms_SambaServerData:/data
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139/tcp
      - 445:445/tcp
    command: '-s "Data;/data;yes;yes;yes;all;none;adminsed" -u "adminsed;519ZsP!y" -p'

  pentaho8:
    image: dh.ics.perm.ru/zs-dms-ose/readycheck/pentaho-8.1-postgres:latest
    depends_on:
      - SrvHBDN
    ports:
      - 12000:8080
    mem_reservation: 4096M
    mem_limit: 6012M
    environment:
      - READYCHECK_URLS=SrvHBDN:5432
      - DB_HOST=SrvHBDN
      - DB_PORT=5432
      - DB_ADMIN_USER=postgres
      - DB_ADMIN_PASS=p@ssw0rd
      - JCR_PASS=519ZsP!y
      - JAVA_OPTS=-Xms2048m -Xmx4096m
      - HIBERNATE_PASS=519ZsP!y
      - QUARTZ_PASS=519ZsP!y
      - LOGSTASH_HOST=${LOGSTASH_HOST}
      - LOGSTASH_PORT=9093
      - LOGSTASH_LOG_LEVEL=ERROR
    extra_hosts:
      - "dms.zspk.perm.ru:172.17.3.30"

  FlexberryServiceBus:
    image: dh.ics.perm.ru/zs-dms-ose/readycheck/esb:${TAG}
    depends_on:
      - SrvHBDN
      - dms-listener
    ports:
      - "7777:7777"
      - "7785:7085"
    environment:
      - READYCHECK_URLS=SrvHBDN:5432 dms-listener:8085
      - XMLTEMPLATES=/opt/flexberry-service-bus/NewPlatform.Flexberry.ServiceBus.WinServiceHost.exe.config
      - DOCKER_HOSTNAME=0.0.0.0
      - ESB_CONNECTION_STRING=Host=SrvHBDN;Port=5432;Database=zsdms_esb;User ID=postgres;Password=p@ssw0rd;
      - ESB_ADDRESS=${HWSB_URL}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
      - LOGSTASH_PORT=${LOGSTASH_PORT}
    extra_hosts:
      - "dms.zspk.perm.ru:10.130.5.176"
      - "srvhnp-app:10.130.5.77"

  dms-listener:
    image: dh.ics.perm.ru/zs-dms-ose/readycheck/dms-listener:${TAG}
    depends_on:
      - SrvHBDN
    environment:
      - READYCHECK_URLS=SrvHBDN:5432
      - XMLTEMPLATES=/dms-listener/ZS.DMS.ServiceBusListenerWinServiceHost.exe.config
      - DMS_CONNECTION_STRING=${DMS_CONNECTION_STRING}
      - DMS_AUDIT_CONNECTION_STRING=${DMS_AUDIT_CONNECTION_STRING}
      - BPM_API_URL=${BPM_API_URL}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
      - LOGSTASH_PORT=${LOGSTASH_PORT}
      - IS_EMAIL_SENDING_ACTIVE=True
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_MAIL_FROM=${SMTP_MAIL_FROM}
      - SMTP_LOGIN=${SMTP_LOGIN}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_ENABLE_SSL=${SMTP_ENABLE_SSL}
      - SMTP_CHECK_CERTIFICATE_REVOCATION=${SMTP_CHECK_CERTIFICATE_REVOCATION}
      - MAIL_ASUD_HOST=https://dms.zspk.perm.ru
      - HWSB_URL=${HWSB_URL}
      - ZS_SUPPORT_EMAIL=abelikova@pminst.ru,Chaschina@pminst.ru
      - IS_NOTIFICATION_ABOUT_PROCESS_FAILURE=False
    ports:
      - 8085:8085
    extra_hosts:
      - "dms.zspk.perm.ru:10.130.5.176"
      - "mail.pminst.ru:10.130.6.30"

  bpm-jbpm:
    image: dh.ics.perm.ru/zs-dms-ose/readycheck/jbpm:${TAG}
    depends_on:
      - SrvHBDN
    environment:
      - READYCHECK_URLS=SrvHBDN:5432
      - NO_PROXY=10.130.*,*.ics.perm.ru
      - DB_HOST=SrvHBDN
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=p@ssw0rd
      - DB_NAME=zsdms_jbpm_2021_10_19
      - JAVA_OPTS_CUSTOM=-Djboss.as.management.blocking.timeout=600 -Xmx4096m -Dnet.logstash.logging.formatter.LogstashUtilFormatter.tags=jbpm
      - LOGSTASH_HOST=${LOGSTASH_HOST}
      - LOGSTASH_PORT=9092
      - LOGSTASH_LOG_LEVEL=INFO
      - retryCount=3
      - retryTimeout=1
      - adminEmail=abelikova@pminst.ru,Chaschina@pminst.ru
    ports:
      - 8001:8001
      - 8180:8080
      - 9990:9990
    mem_reservation: 2048M
    mem_limit: 6012M
    volumes:
      - ZsDms_jbpmGit_new:/wildfly/bin/.niogit
      - ZsDms_jbpmRep_new:/wildfly/bin/repositories
      - ZsDms_jbpmMaven_new:/root/.m2/repository
      - /home/ics/jbpm_additional_config/application-roles.properties:/wildfly/standalone/configuration/application-roles.properties
      - /home/ics/jbpm_additional_config/application-users.properties:/wildfly/standalone/configuration/application-users.properties
      - /home/ics/jbpm_additional_config/mgmt-groups.properties:/wildfly/standalone/configuration/mgmt-groups.properties
      - /home/ics/jbpm_additional_config/mgmt-users.properties:/wildfly/standalone/configuration/mgmt-users.properties
      - /home/ics/jbpm_additional_config/roles.properties:/wildfly/standalone/configuration/roles.properties
      - /home/ics/jbpm_additional_config/users.properties:/wildfly/standalone/configuration/users.properties
    extra_hosts:
      - "dms.zspk.perm.ru:10.130.5.176"

  NetCoreServices:
    image: dh.ics.perm.ru/zs/netcore_services:${TAG}
    ports:
      - 11180:5200
    environment:
      - NCS_PDFServiceUri=http://SrvHNP-app:9911/api/PDFConvert/GetPDF
    extra_hosts:
      - "SrvHNP-app:10.130.5.105"
      - "dms.zspk.perm.ru:10.130.5.176"

  clickhouse:
    image: yandex/clickhouse-server:21.9.2.17
    volumes:
      - "/home/ics/clickhouse/graphite_rollup.xml:/etc/clickhouse-server/config.d/graphite_rollup.xml"
      - "/home/ics/clickhouse/clickhouse_metrics.xml:/etc/clickhouse-server/config.d/clickhouse_metrics.xml"
      #- "/home/ics/clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "/home/ics/clickhouse/data/:/var/lib/clickhouse/"
      - "/home/ics/clickhouse/data/:/var/log/clickhouse-server/"
    ports:
      - "8123:8123"

  logstash:
    image: dh.ics.perm.ru/zs-dms-ose/logstash:latest
    depends_on:
      - clickhouse
    environment:
      READYCHECK_URLS: clickhouse:8123
      CLICK_HOUSE_AUTH_HEADER: "Basic ZGVmYXVsdDo="
      CLICK_HOUSE_HOST: "http://clickhouse:8123/"
      CLICK_HOUSE_LOGS_TABLE: "dms.logs"
    ports:
      - 9090:9090
      - 9091:9091/udp
      - 9092:9092
      - 9093:9093

  graphouse:
    image: dh.ics.perm.ru/zs-dms-ose/readycheck/graphouse:latest
    depends_on:
      - clickhouse
    environment:
      - READYCHECK_URLS="clickhouse:8123"
      - GH__CLICKHOUSE__HOSTS=clickhouse
      - GH__CLICKHOUSE__RETENTION_CONFIG=graphite_rollup
    ports:
      - "2003:2003"
      - "2005:2005"

  graphite-web:
    image: dh.ics.perm.ru/zs-dms-ose/readycheck/graphite-web:latest
    depends_on:
      - graphouse
    environment:
      - READYCHECK_URLS=graphouse:2005"
      - GRAPHOUSE_URL=http://graphouse:2005
    ports:
      - "8088:80"

  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  DB:
  ZsDms_jbpmGit_new:
    external: true
  ZsDms_jbpmRep_new:
    external: true
  ZsDms_jbpmMaven_new:
    external: true
  ZsDms_WebDavServerFiles:
    external: true
  ZsDms_sharedData:
    external: true
  ZsDms_SambaServerData:
    external: true

